/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-04-10 01:40:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1680738812000L));
    _jspx_dependants.put("jar:file:/Users/deokkeun/Desktop/YoSangSo-main/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/yosangso/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/Users/deokkeun/Desktop/YoSangSo-main/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/yosangso/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/sql.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/Users/deokkeun/Desktop/YoSangSo-main/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/yosangso/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsql_005fsetDataSource_0026_005fvar_005fuser_005furl_005fpassword_005fdriver_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsql_005fquery_0026_005fvar_005fdataSource;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fsql_005fsetDataSource_0026_005fvar_005fuser_005furl_005fpassword_005fdriver_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsql_005fquery_0026_005fvar_005fdataSource = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fsql_005fsetDataSource_0026_005fvar_005fuser_005furl_005fpassword_005fdriver_005fnobody.release();
    _005fjspx_005ftagPool_005fsql_005fquery_0026_005fvar_005fdataSource.release();
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <!-- 반응형 페이지 필요 -->\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    \n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/index.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/main-style.css\">\n");
      out.write("    <script src=\"https://kit.fontawesome.com/881d1deef7.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("    \n");
      out.write("    <!-- 슬라이더 파일다운받은거 -->\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("    \n");
      out.write("    <title>index</title>\n");
      out.write("    \n");
      out.write("    <!--탑 버튼 & 스크립트 html 부분-->\n");
      out.write("    \n");
      out.write("    <!--탑 버튼-->\n");
      out.write("    <a id=\"topBtn\" href=\"#\"> \n");
      out.write("        <i class=\"fa-solid fa-angles-up fa-2x\"></i>\n");
      out.write("    </a> \n");
      out.write("    \n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      if (_jspx_meth_sql_005fsetDataSource_005f0(_jspx_page_context))
        return;
      out.write('\n');
      out.write('\n');
      out.write('\n');
      if (_jspx_meth_sql_005fquery_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("    <!-- 헤더, 컨텐츠 -->\n");
      out.write("    <main>\n");
      out.write("  \n");
      out.write("\n");
      out.write("    	<!-- 헤더 -->\n");
      out.write("    	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\n");
      out.write("    \n");
      out.write("    \n");
      out.write("        <!-- 내용 작성 공간입니다.(template2) -->\n");
      out.write("        <!-- content 전체 감싸는 영역 -->\n");
      out.write("        <section class=\"content-container\">\n");
      out.write("        \n");
      out.write("            <!-- 왼쪽사이드 -->\n");
      out.write("            <section class=\"leftSide\">\n");
      out.write("            </section>\n");
      out.write("            \n");
      out.write("			\n");
      out.write("\n");
      out.write("            <!-- 가운데페이지 -->\n");
      out.write("            <section class=\"center\">\n");
      out.write("\n");
      out.write("\n");
      out.write("                <!-- 1. 메인페이지 슬라이더 사진 영역 -->\n");
      out.write("                <section class=\"mainViewPhoto\">\n");
      out.write("                                 \n");
      out.write("                    <div id=\"visual\">\n");
      out.write("                        <div class=\"on\">\n");
      out.write("                            <img src=\"resources/image/index/메인슬라이더1편집.jpg\"  width=\"100%\">\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div>\n");
      out.write("                            <img src=\"resources/image/index/메인슬라이더2편집.jpg\" width=\"100%\">\n");
      out.write("                        </div>	\n");
      out.write(" 				\n");
      out.write("                    	<div>\n");
      out.write("                	        <img src=\"resources/image/index/메인슬라이더3편집.png\" width=\"100%\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                         \n");
      out.write("\n");
      out.write("                </section>\n");
      out.write("\n");
      out.write("			\n");
      out.write("\n");
      out.write("                <!-- 2 베스트부분 시작 -->\n");
      out.write("                <section class=\"bestPart\">\n");
      out.write("\n");
      out.write("                    <!-- 2-1 베스트 글씨 -->\n");
      out.write("                    <div class=\"mainFont bestFont\">베스트</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <!-- 2-2 베스트 제품 -->\n");
      out.write("                    <div class=\"bestItem\"> \n");
      out.write("\n");
      out.write("					\n");
      out.write("						                        \n");
      out.write("                        <!-- 베스트제품1 -->\n");
      out.write("                     \n");
      out.write("                        <div class=\"BNitem Bitem1\">  \n");
      out.write("                            <a href=\"product/productDetail?ProductNo=1\">  \n");
      out.write("                                <div class=\"BNitemPic bestItem1Pic\"> \n");
      out.write("                                    <figcaption>\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rs.rows[0]['PRODUCT_NM']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"</figcaption> \n");
      out.write("                                    <img src=\"resources/image/product/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rs.rows[0]['PRODUCT_NM']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".jpg\"  \n");
      out.write("                                        alt=\"제품사진\" id=\"bestItemPhot1\"> \n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("                                <div class=\"BNitemName bestItem1Name\">\n");
      out.write("                                    <a href=\"#\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rs.rows[0]['PRODUCT_NM']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>\n");
      out.write("                                </div> \n");
      out.write("                            \n");
      out.write("                                <div class=\"BNitemPrice bestItem1Price\">");
      if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_page_context))
        return;
      out.write("원</div>\n");
      out.write("                        </div>                          \n");
      out.write("\n");
      out.write("                                                 \n");
      out.write("                        <!-- 베스트제품2 -->  \n");
      out.write("                        <div class=\"BNitem Bitem2\">  \n");
      out.write("                            <a href=\"#\">  \n");
      out.write("                                <div class=\"BNitemPic bestItem2Pic\"> \n");
      out.write("                                    <figcaption>베스트제품2<br><br> 상세설명칸<br><br> 입니다 </figcaption> \n");
      out.write("                                    <img src=\"resources/image/product/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rs.rows[10]['PRODUCT_NM']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".jpg\"  \n");
      out.write("                                        alt=\"제품사진\" id=\"bestItemPhoto2\"> \n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("                                <div class=\"BNitemName bestItem2Name\">\n");
      out.write("                                    <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>\n");
      out.write("                                </div> \n");
      out.write("                            \n");
      out.write("                                <div class=\"BNitemPrice bestItem2Price\">");
      if (_jspx_meth_fmt_005fformatNumber_005f1(_jspx_page_context))
        return;
      out.write("원</div>\n");
      out.write("                        </div>                       \n");
      out.write("\n");
      out.write("\n");
      out.write("                        <!-- 베스트제품3 -->\n");
      out.write("                        <div class=\"BNitem Bitem3\">\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <div class=\"BNitemPic bestItem3Pic\">\n");
      out.write("                                    <figcaption>베스트제품3<br><br> 상세설명칸<br><br> 입니다 </figcaption>\n");
      out.write("                                    <img src=\"resources/image/product/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rs.rows[0]['PRODUCT_NM']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".jpg\" \n");
      out.write("                                    alt=\"제품사진\" id=\"bestItemPhoto3\">\n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("\n");
      out.write("                                <div class=\"BNitemName bestItem3Name\">\n");
      out.write("                                    <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>  \n");
      out.write("                                </div>\n");
      out.write("\n");
      out.write("                                <div class=\"BNitemPrice bestItem3Price\">75,000원</div>  \n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <!-- 베스트제품4 -->\n");
      out.write("                        <div class=\"BNitem Bitem4\">\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <div class=\"BNitemPic bestItem1Pic\">\n");
      out.write("                                    <figcaption>베스트제품4<br><br> 상세설명칸<br><br> 입니다 </figcaption>\n");
      out.write("                                    <img src=\"resources/image/index/제품_오쏘뮬.jpg\" \n");
      out.write("                                    alt=\"제품사진\" id=\"bestItemPhoto4\">\n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("\n");
      out.write("                                <div class=\"BNitemName bestItem1Name\">\n");
      out.write("                                    <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분) </a>\n");
      out.write("                                </div>        \n");
      out.write("\n");
      out.write("                                <div class=\"BNitemPrice bestItem4Price\">75,000원</div>\n");
      out.write("                        </div> \n");
      out.write("                    \n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                    \n");
      out.write("                    <!-- 2-3 베스트제품더보기 -->\n");
      out.write("                    <div>\n");
      out.write("                        <div class=\"more bestMore\">\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/bestProduct\">더보기 \n");
      out.write("                            		<i class=\"fa-solid fa-angles-right\" id=\"allow\"></i>\n");
      out.write("                            </a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                </section>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                <!-- 3 신제품부분 시작 -->\n");
      out.write("                <section class=\"newPart\">\n");
      out.write("\n");
      out.write("                    <!-- 3-1 신제품 글씨 -->\n");
      out.write("                    <div class=\"mainFont newFont\">신제품</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <!-- 3-2 신제품 순 -->\n");
      out.write("                    <div class=\"newItem\">\n");
      out.write("\n");
      out.write("                        <!-- 신제품1 -->\n");
      out.write("                        <div class=\"BNitem Nitem1\">\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <div class=\"BNitemPic newItem1Pic\">\n");
      out.write("                                    <figcaption>신제품1<br><br> 상세설명칸<br><br> 입니다 </figcaption>\n");
      out.write("                                    <img src=\"resources/image/index/제품_오쏘뮬.jpg\" \n");
      out.write("                                        alt=\"제품사진\" id=\"newItemPhoto1\">  \n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("                                <div class=\"BNitemName newItem1Name\">\n");
      out.write("                                    <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a> \n");
      out.write("                                </div>\n");
      out.write("                           \n");
      out.write("                                <div class=\"BNitemPrice newItem1Price\">65,000원</div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <!-- 신제품2 -->\n");
      out.write("                        <div class=\"BNitem Nitem2\">\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <div class=\"BNitemPic newItem2Pic\">\n");
      out.write("                                    <figcaption>신제품2<br><br> 상세설명칸<br><br> 입니다 </figcaption>\n");
      out.write("                                    <img src=\"resources/image/index/제품_오쏘뮬.jpg\" \n");
      out.write("                                        alt=\"제품사진\" id=\"newItemPhoto2\">\n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("                                <div class=\"BNitemName newItem2Name\">\n");
      out.write("                                    <a href=\"#\">신제품2 설명</a>\n");
      out.write("                                </div>\n");
      out.write("                            \n");
      out.write("                                <div class=\"BNitemPrice newItem2Price\">신제품2 가격</div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <!-- 신제품3 -->\n");
      out.write("                        <div class=\"BNitem Nitem3\">\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <div class=\"BNitemPic newItem3Pic\">\n");
      out.write("                                    <figcaption>신제품3<br><br> 상세설명칸<br><br> 입니다 </figcaption>\n");
      out.write("                                    <img src=\"resources/image/index/제품_오쏘뮬.jpg\" \n");
      out.write("                                        alt=\"제품사진\" id=\"newItemPhoto3\">\n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("                                <div class=\"BNitemName newItem3Name\">\n");
      out.write("                                    <a href=\"#\">신제품3 설명</a>\n");
      out.write("                                </div>\n");
      out.write("\n");
      out.write("                                <div class=\"BNitemPrice newItem3Price\">신제품3 가격</div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <!-- 신제품4 -->\n");
      out.write("                        <div class=\"BNitem Nitem4\">\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <div class=\"BNitemPic newItem4Pic\">\n");
      out.write("                                    <figcaption>신제품4<br><br> 상세설명칸<br><br> 입니다 </figcaption>\n");
      out.write("                                    <img src=\"resources/image/index/제품_오쏘뮬.jpg\" \n");
      out.write("                                        alt=\"제품사진\" id=\"newItemPhoto4\">\n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("                                <div class=\"BNitemName newItem4Name\">\n");
      out.write("                                    <a href=\"#\">신제품4 설명</a>\n");
      out.write("                                </div>\n");
      out.write("                              \n");
      out.write("                                <div class=\"BNitemPrice newItem4Price\">신제품4 가격</div>\n");
      out.write("                        </div>\n");
      out.write("                    \n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <!-- 3-3 신제품 더보기 -->\n");
      out.write("                    <div>\n");
      out.write("                        <div class=\"more newMore\">\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/newProduct\">더보기 <i class=\"fa-solid fa-angles-right\" id=\"allow\"></i></a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                <!-- 신제품부분 끝  -->\n");
      out.write("                </section>\n");
      out.write("            \n");
      out.write("\n");
      out.write("                \n");
      out.write("                \n");
      out.write("                <!-- 4 제품부분 시작 -->\n");
      out.write("                <section class=\"itemPart\">\n");
      out.write("\n");
      out.write("                    <!-- 4-1 제품글씨 -->\n");
      out.write("                    <div class=\"mainFont itemFont\">제품</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <!-- 4-2 제품모음 -->\n");
      out.write("                    <div class=\"itemGather\">\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <!-- 제품 1 ~3 -->\n");
      out.write("                        <div class=\"itemFirst\">\n");
      out.write("\n");
      out.write("\n");
      out.write("                            <!-- 제품1 -->\n");
      out.write("                            <div class=\"item item1\">\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    <div class=\"itemPic item1Pic\">\n");
      out.write("                                        <figcaption>제품1<br><br>상세설명칸<br><br>입니다</figcaption>\n");
      out.write("                                        <img src=\"resources/image/index/제품_오쏘뮬.jpg\" \n");
      out.write("                                            alt=\"이미지입니다\" id=\"itemPhoto1\">\n");
      out.write("                                    </div>\n");
      out.write("                                </a>\n");
      out.write("                                \n");
      out.write("                                    <div class=\"itemName item1Name\">\n");
      out.write("                                        <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>\n");
      out.write("                                    </div>\n");
      out.write("\n");
      out.write("                                    <div class=\"itemPrice item1Price\">16,000원</div>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                            <!-- 제품2 -->\n");
      out.write("                            <div class=\"item item2\">\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    <div class=\"itemPic item2Pic\">\n");
      out.write("                                        <figcaption>제품2<br><br>상세설명칸<br><br>입니다</figcaption>\n");
      out.write("                                        <img src=\"resources/image/index/제품_오쏘뮬.jpg\" \n");
      out.write("                                            alt=\"이미지입니다\" id=\"itemPhoto2\">\n");
      out.write("                                    </div>\n");
      out.write("                                </a>    \n");
      out.write("\n");
      out.write("                                    <div class=\"itemName item2Name\">\n");
      out.write("                                        <a href=\"\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>\n");
      out.write("                                    </div>\n");
      out.write("\n");
      out.write("                                    <div class=\"itemPrice item2Price\">16,000원</div>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                            <!-- 제품3 -->\n");
      out.write("                            <div class=\"item item3\">\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    <div class=\"itemPic item3Pic\">\n");
      out.write("                                        <figcaption>제품3<br><br>상세설명칸<br><br>입니다</figcaption>\n");
      out.write("                                        <img src=\"resources/image/index/제품_오쏘뮬.jpg\" \n");
      out.write("                                            alt=\"이미지입니다\" id=\"itemPhoto3\">\n");
      out.write("                                    </div>\n");
      out.write("                                </a>\n");
      out.write("                               \n");
      out.write("\n");
      out.write("                                    <div class=\"itemName item3Name\">\n");
      out.write("                                        <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>\n");
      out.write("                                    </div>\n");
      out.write("\n");
      out.write("                                    <div class=\"itemPrice item3Price\">16,000원</div>\n");
      out.write("                            </div>\n");
      out.write("                        \n");
      out.write("                        \n");
      out.write("                        </div>\n");
      out.write("                    \n");
      out.write("\n");
      out.write("\n");
      out.write("                        <!-- 제품 4~6 -->\n");
      out.write("                        <div class=\"itemSecond\">\n");
      out.write("\n");
      out.write("\n");
      out.write("                            <!-- 제품4 -->\n");
      out.write("                            <div class=\"item item4\">\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    <div class=\"itemPic item4Pic\">\n");
      out.write("                                        <figcaption>제품4<br><br>상세설명칸<br><br>입니다</figcaption>\n");
      out.write("                                        <img src=\"resources/image/index/제품_오쏘뮬.jpg\" \n");
      out.write("                                            alt=\"이미지입니다\" id=\"itemPhoto4\"> \n");
      out.write("                                    </div>\n");
      out.write("                                </a>\n");
      out.write("\n");
      out.write("                                    <div class=\"itemName item4Name\">\n");
      out.write("                                        <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>\n");
      out.write("                                    </div>\n");
      out.write("\n");
      out.write("                                    <div class=\"itemPrice item4Price\">16,000원</div>    \n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                            <!-- 제품5 -->\n");
      out.write("                            <div class=\"item item5\">\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    <div class=\"itemPic item5Pic\">\n");
      out.write("                                        <figcaption>제품5<br><br>상세설명칸<br><br>입니다</figcaption>\n");
      out.write("                                        <img src=\"resources/image/index/제품_오쏘뮬.jpg\"  \n");
      out.write("                                            alt=\"이미지입니다\" id=\"itemPhoto5\">   \n");
      out.write("                                    </div>\n");
      out.write("                                </a>\n");
      out.write("\n");
      out.write("                                    <div class=\"itemName item5Name\">\n");
      out.write("                                        <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>\n");
      out.write("                                    </div>\n");
      out.write("\n");
      out.write("                                    <div class=\"itemPrice item5Price\">16,000원</div>  \n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                            <!-- 제품6 -->\n");
      out.write("                            <div class=\"item item6\">\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    <div class=\"itemPic item6Pic\">\n");
      out.write("                                        <figcaption>제품6<br><br>상세설명칸<br><br>입니다</figcaption>\n");
      out.write("                                        <img src=\"resources/image/index/제품_오쏘뮬.jpg\"  \n");
      out.write("                                            alt=\"이미지입니다\" id=\"itemPhoto6\">\n");
      out.write("                                    </div>\n");
      out.write("                                </a>\n");
      out.write("\n");
      out.write("                                    <div class=\"itemName item6Name\">\n");
      out.write("                                        <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>\n");
      out.write("                                    </div>\n");
      out.write("\n");
      out.write("                                    <div class=\"itemPrice item6Price\">16,000원</div> \n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                        \n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <!-- 제품7~9 -->\n");
      out.write("                        <div class=\"itemThird\">\n");
      out.write("\n");
      out.write("\n");
      out.write("                            <!-- 제품7 -->\n");
      out.write("                            <div class=\"item item7\">\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    <div class=\"itemPic item7Pic\">\n");
      out.write("                                        <figcaption>제품7<br><br>상세설명칸<br><br>입니다</figcaption>\n");
      out.write("                                        <img src=\"resources/image/index/제품_오쏘뮬.jpg\"  \n");
      out.write("                                            alt=\"이미지입니다\" id=\"itemPhoto7\">\n");
      out.write("                                    </div>\n");
      out.write("                                </a>\n");
      out.write("                                \n");
      out.write("                                    <div class=\"itemName item7Name\">\n");
      out.write("                                        <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>\n");
      out.write("                                    </div>\n");
      out.write("\n");
      out.write("                                    <div class=\"itemPrice item7Price\">16,000원</div>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                            <!-- 제품8 -->\n");
      out.write("                            <div class=\"item item8\">\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    <div class=\"itemPic item8Pic\">\n");
      out.write("                                        <figcaption>제품8<br><br>상세설명칸<br><br>입니다</figcaption>\n");
      out.write("                                        <img src=\"resources/image/index/제품_오쏘뮬.jpg\" \n");
      out.write("                                            alt=\"이미지입니다\" id=\"itemPhoto8\">\n");
      out.write("                                    </div>\n");
      out.write("                                </a>\n");
      out.write("\n");
      out.write("                                    <div class=\"itemName item8Name\">\n");
      out.write("                                        <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>\n");
      out.write("                                    </div>\n");
      out.write("\n");
      out.write("                                    <div class=\"itemPrice item8Price\">16,000원</div> \n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                            <!-- 제품9 -->\n");
      out.write("                            <div class=\"item item9\">\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    <div class=\"itemPic item9Pic\">\n");
      out.write("                                        <figcaption>제품8<br><br>상세설명칸<br><br>입니다</figcaption>\n");
      out.write("                                        <img src=\"resources/image/index/제품_오쏘뮬.jpg\" \n");
      out.write("                                            alt=\"이미지입니다\" id=\"itemPhoto9\">\n");
      out.write("                                    </div>\n");
      out.write("                                </a>\n");
      out.write("\n");
      out.write("                                    <div class=\"itemName item9Name\">\n");
      out.write("                                        <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>\n");
      out.write("                                    </div>\n");
      out.write("\n");
      out.write("                                    <div class=\"itemPrice item9Price\">16,000원</div> \n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                \n");
      out.write("                    <!-- 4-3 제품더보기 더보기 -->\n");
      out.write("                    <div class=\"itemMore\"> \n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/allProduct\">더보기 <i class=\"fa-solid fa-angles-right\" id=\"allow\"> </i></a>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                <!-- 제품부분 끝 -->\n");
      out.write("                </section>\n");
      out.write("            \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("            <!-- 가운데페이지 끝 -->\n");
      out.write("            </section>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("            <!-- 오른쪽사이드바 -->\n");
      out.write("            <section class=\"rightSide\">\n");
      out.write("\n");
      out.write("                 <!-- 인체사진 플로팅바-->\n");
      out.write("                 <div class=\"floating\">\n");
      out.write("                    <a href=\"product/person\"> \n");
      out.write("                        <img id=\"people\" src=\"resources/image/index/인체이미지누끼.png\" >\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("            \n");
      out.write("            </section>\n");
      out.write("\n");
      out.write("        </section>\n");
      out.write("        <!-- content 전체 감싸는 영역 끝 -->\n");
      out.write("\n");
      out.write("       \n");
      out.write("    <!-- 헤더, 컨텐츠 끝 -->\n");
      out.write("    </main>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- 푸터 -->\n");
      out.write("  	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("	<!-- jQuery 라이브러리 추가 -->\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\" integrity=\"sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=\" crossorigin=\"anonymous\"></script>\n");
      out.write("   \n");
      out.write("   	<script>\n");
      out.write(" // Image 객체를 참조한후 Image 객체의 속성인 src 로 이미지 주소를 담습니다.  \n");
      out.write("	var img1 = new Image();\n");
      out.write("	img1.src = 'resources/image/index/메인슬라이더1편집.jpg';\n");
      out.write("	var img2 = new Image();\n");
      out.write("	img2.src = 'resources/image/index/메인슬라이더2편집.jpg';\n");
      out.write("	var img3 = new Image();\n");
      out.write("	img3.src = 'resources/image/index/메인슬라이더3편집.png';\n");
      out.write("\n");
      out.write("// 이미지 총 갯수를 maxCount 에 셋팅 해줍니다.\n");
      out.write("	var maxCount = 3;\n");
      out.write("	var count = 1;   \n");
      out.write("    \n");
      out.write("	function slideFun() {\n");
      out.write("	    if( count == (maxCount + 1) ) { count = 1; } \n");
      out.write("	    document.imgimg.src= eval( \"img\" + count + \".src\");\n");
      out.write("	    count++;\n");
      out.write("	}\n");
      out.write("// setInerval 메소드로 slideFun() 함수를 1초 마다 실행 합니다.   \n");
      out.write("	function startFun() {\n");
      out.write("	    slideTime = setInterval(\"slideFun()\",1000);\n");
      out.write("	}\n");
      out.write("// 이미지에 마우스 오버시 실행중인 setInerval 를 clearInterval 로 정지 합니다.\n");
      out.write("	function stopFun() {\n");
      out.write("	    clearInterval(slideTime);    \n");
      out.write("	}\n");
      out.write("// 브라우저 호환(크로스브라우징)을 위해 메소드 제공 여부를 체크 합니다. \n");
      out.write("// 이미지에 마우스오버시 \"정지\", 마우스아웃시 \"시작\" 이벤트를 적용합니다.\n");
      out.write("	if (document.addEventListener){\n");
      out.write("	    document.imgimg.addEventListener(\"mouseover\",stopFun,false);\n");
      out.write("	    document.imgimg.addEventListener(\"mouseout\",startFun,false);\n");
      out.write("	} else {\n");
      out.write("	    document.imgimg.attachEvent(\"onmouseover\",stopFun);\n");
      out.write("	    document.imgimg.attachEvent(\"onmouseout\",startFun);\n");
      out.write("	}\n");
      out.write("// 페이지 로딩시 startFun() 함수를 실행 합니다.\n");
      out.write("startFun();\n");
      out.write("\n");
      out.write("\n");
      out.write("   	\n");
      out.write("   	</script>\n");
      out.write("    <!-- main.js 연결 -->\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/index.js\"></script>\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/main.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_sql_005fsetDataSource_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sql:setDataSource
    org.apache.taglibs.standard.tag.rt.sql.SetDataSourceTag _jspx_th_sql_005fsetDataSource_005f0 = (org.apache.taglibs.standard.tag.rt.sql.SetDataSourceTag) _005fjspx_005ftagPool_005fsql_005fsetDataSource_0026_005fvar_005fuser_005furl_005fpassword_005fdriver_005fnobody.get(org.apache.taglibs.standard.tag.rt.sql.SetDataSourceTag.class);
    boolean _jspx_th_sql_005fsetDataSource_005f0_reused = false;
    try {
      _jspx_th_sql_005fsetDataSource_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sql_005fsetDataSource_005f0.setParent(null);
      // /index.jsp(35,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sql_005fsetDataSource_005f0.setVar("conn");
      // /index.jsp(35,0) name = driver type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sql_005fsetDataSource_005f0.setDriver("oracle.jdbc.driver.OracleDriver");
      // /index.jsp(35,0) name = url type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sql_005fsetDataSource_005f0.setUrl("jdbc:oracle:thin:@//112.220.137.37:1521/xe");
      // /index.jsp(35,0) name = user type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sql_005fsetDataSource_005f0.setUser("yosangso");
      // /index.jsp(35,0) name = password type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sql_005fsetDataSource_005f0.setPassword("yosangso");
      int _jspx_eval_sql_005fsetDataSource_005f0 = _jspx_th_sql_005fsetDataSource_005f0.doStartTag();
      if (_jspx_th_sql_005fsetDataSource_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsql_005fsetDataSource_0026_005fvar_005fuser_005furl_005fpassword_005fdriver_005fnobody.reuse(_jspx_th_sql_005fsetDataSource_005f0);
      _jspx_th_sql_005fsetDataSource_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sql_005fsetDataSource_005f0, _jsp_getInstanceManager(), _jspx_th_sql_005fsetDataSource_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sql_005fquery_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sql:query
    org.apache.taglibs.standard.tag.rt.sql.QueryTag _jspx_th_sql_005fquery_005f0 = (org.apache.taglibs.standard.tag.rt.sql.QueryTag) _005fjspx_005ftagPool_005fsql_005fquery_0026_005fvar_005fdataSource.get(org.apache.taglibs.standard.tag.rt.sql.QueryTag.class);
    boolean _jspx_th_sql_005fquery_005f0_reused = false;
    try {
      _jspx_th_sql_005fquery_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sql_005fquery_005f0.setParent(null);
      // /index.jsp(43,0) name = var type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sql_005fquery_005f0.setVar("rs");
      // /index.jsp(43,0) name = dataSource type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sql_005fquery_005f0.setDataSource((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${conn}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_sql_005fquery_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_sql_005fquery_005f0 = _jspx_th_sql_005fquery_005f0.doStartTag();
        if (_jspx_eval_sql_005fquery_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          if (_jspx_eval_sql_005fquery_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            _jspx_push_body_count_sql_005fquery_005f0[0]++;
            out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_sql_005fquery_005f0);
          }
          do {
            out.write("\n");
            out.write("select * from product\n");
            int evalDoAfterBody = _jspx_th_sql_005fquery_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
          if (_jspx_eval_sql_005fquery_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = _jspx_page_context.popBody();
            _jspx_push_body_count_sql_005fquery_005f0[0]--;
          }
        }
        if (_jspx_th_sql_005fquery_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sql_005fquery_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sql_005fquery_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sql_005fquery_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fsql_005fquery_0026_005fvar_005fdataSource.reuse(_jspx_th_sql_005fquery_005f0);
      _jspx_th_sql_005fquery_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sql_005fquery_005f0, _jsp_getInstanceManager(), _jspx_th_sql_005fquery_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f0.setParent(null);
      // /index.jsp(117,72) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rs.rows[0]['PRICE']}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /index.jsp(117,72) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setPattern("#,###");
      int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
      _jspx_th_fmt_005fformatNumber_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f1_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f1.setParent(null);
      // /index.jsp(134,72) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rs.rows[1]['PRICE']}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /index.jsp(134,72) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f1.setPattern("#,###");
      int _jspx_eval_fmt_005fformatNumber_005f1 = _jspx_th_fmt_005fformatNumber_005f1.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f1);
      _jspx_th_fmt_005fformatNumber_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f1_reused);
    }
    return false;
  }
}
