/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-04-16 04:02:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1680738812000L));
    _jspx_dependants.put("jar:file:/Users/deokkeun/Desktop/YoSangSo-main/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/yosangso/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      if (true) {
        _jspx_page_context.forward("main");
        return;
      }
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<sql:setDataSource var= \"conn\" \n");
      out.write("	driver = \"oracle.jdbc.driver.OracleDriver\"\n");
      out.write("	url=\"jdbc:oracle:thin:@//112.220.137.37:1521/xe\"\n");
      out.write("	user=\"yosangso\"\n");
      out.write("	password=\"yosangso\"\n");
      out.write("/>\n");
      out.write("\n");
      out.write("\n");
      out.write("<sql:query var =\"rs\" dataSource=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${conn}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("select * from product\n");
      out.write("</sql:query>\n");
      out.write("\n");
      out.write("    <!-- 헤더, 컨텐츠 -->\n");
      out.write("    <main>\n");
      out.write("  \n");
      out.write("\n");
      out.write("    	<!-- 헤더 -->\n");
      out.write("    	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\n");
      out.write("    \n");
      out.write("    \n");
      out.write("        <!-- 내용 작성 공간입니다.(template2) -->\n");
      out.write("        <!-- content 전체 감싸는 영역 -->\n");
      out.write("        <section class=\"content-container\">\n");
      out.write("        \n");
      out.write("            <!-- 왼쪽사이드 -->\n");
      out.write("            <section class=\"leftSide\">\n");
      out.write("            </section>\n");
      out.write("            \n");
      out.write("			\n");
      out.write("\n");
      out.write("            <!-- 가운데페이지 -->\n");
      out.write("            <section class=\"center\">\n");
      out.write("\n");
      out.write("                <!-- 1. 메인페이지 슬라이더 사진 영역 -->\n");
      out.write("                <section class=\"mainViewPhoto\">\n");
      out.write("                                 \n");
      out.write("                    <div id=\"visual\">\n");
      out.write("                        <div class=\"on\">\n");
      out.write("                            <img src=\"resources/image/index/메인슬라이더1편집.jpg\"  width=\"100%\">\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div>\n");
      out.write("                            <img src=\"resources/image/index/메인슬라이더2편집.jpg\" width=\"100%\">\n");
      out.write("                        </div>	\n");
      out.write(" 				\n");
      out.write("                    	<div>\n");
      out.write("                	        <img src=\"resources/image/index/메인슬라이더3편집.png\" width=\"100%\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                         \n");
      out.write("\n");
      out.write("                </section>\n");
      out.write("\n");
      out.write("			\n");
      out.write("\n");
      out.write("                <!-- 2 베스트부분 시작 -->\n");
      out.write("                <section class=\"bestPart\">\n");
      out.write("\n");
      out.write("                    <!-- 2-1 베스트 글씨 -->\n");
      out.write("                    <div class=\"mainFont bestFont\">베스트</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <!-- 2-2 베스트 제품 -->\n");
      out.write("                    <div class=\"bestItem\"> \n");
      out.write("\n");
      out.write("					\n");
      out.write("						                        \n");
      out.write("                        <!-- 베스트제품1 -->\n");
      out.write("                     \n");
      out.write("                        <div class=\"BNitem Bitem1\">  \n");
      out.write("                            <a href=\"product/productDetail?ProductNo=1\">  \n");
      out.write("                                <div class=\"BNitemPic bestItem1Pic\"> \n");
      out.write("                                    <figcaption>\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rs.rows[0]['PRODUCT_NM']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"</figcaption> \n");
      out.write("                                    <img src=\"resources/image/product/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rs.rows[0]['PRODUCT_NM']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".jpg\"  \n");
      out.write("                                        alt=\"제품사진\" id=\"bestItemPhot1\"> \n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("                                <div class=\"BNitemName bestItem1Name\">\n");
      out.write("                                    <a href=\"#\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rs.rows[0]['PRODUCT_NM']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>\n");
      out.write("                                </div> \n");
      out.write("                            \n");
      out.write("                                <div class=\"BNitemPrice bestItem1Price\"><fmt:formatNumber value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rs.rows[0]['PRICE']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" pattern=\"#,###\"/>원</div>\n");
      out.write("                        </div>                          \n");
      out.write("\n");
      out.write("                                                 \n");
      out.write("                        <!-- 베스트제품2 -->  \n");
      out.write("                        <div class=\"BNitem Bitem2\">  \n");
      out.write("                            <a href=\"#\">  \n");
      out.write("                                <div class=\"BNitemPic bestItem2Pic\"> \n");
      out.write("                                    <figcaption>베스트제품2<br><br> 상세설명칸<br><br> 입니다 </figcaption> \n");
      out.write("                                    <img src=\"resources/image/product/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rs.rows[10]['PRODUCT_NM']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".jpg\"  \n");
      out.write("                                        alt=\"제품사진\" id=\"bestItemPhoto2\"> \n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("                                <div class=\"BNitemName bestItem2Name\">\n");
      out.write("                                    <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>\n");
      out.write("                                </div> \n");
      out.write("                            \n");
      out.write("                                <div class=\"BNitemPrice bestItem2Price\"><fmt:formatNumber value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rs.rows[1]['PRICE']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" pattern=\"#,###\"/>원</div>\n");
      out.write("                        </div>                       \n");
      out.write("\n");
      out.write("\n");
      out.write("                        <!-- 베스트제품3 -->\n");
      out.write("                        <div class=\"BNitem Bitem3\">\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <div class=\"BNitemPic bestItem3Pic\">\n");
      out.write("                                    <figcaption>베스트제품3<br><br> 상세설명칸<br><br> 입니다 </figcaption>\n");
      out.write("                                    <img src=\"resources/image/product/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rs.rows[0]['PRODUCT_NM']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".jpg\" \n");
      out.write("                                    alt=\"제품사진\" id=\"bestItemPhoto3\">\n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("\n");
      out.write("                                <div class=\"BNitemName bestItem3Name\">\n");
      out.write("                                    <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>  \n");
      out.write("                                </div>\n");
      out.write("\n");
      out.write("                                <div class=\"BNitemPrice bestItem3Price\">75,000원</div>  \n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <!-- 베스트제품4 -->\n");
      out.write("                        <div class=\"BNitem Bitem4\">\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <div class=\"BNitemPic bestItem1Pic\">\n");
      out.write("                                    <figcaption>베스트제품4<br><br> 상세설명칸<br><br> 입니다 </figcaption>\n");
      out.write("                                    <img src=\"resources/image/index/제품_오쏘뮬.jpg\" \n");
      out.write("                                    alt=\"제품사진\" id=\"bestItemPhoto4\">\n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("\n");
      out.write("                                <div class=\"BNitemName bestItem1Name\">\n");
      out.write("                                    <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분) </a>\n");
      out.write("                                </div>        \n");
      out.write("\n");
      out.write("                                <div class=\"BNitemPrice bestItem4Price\">75,000원</div>\n");
      out.write("                        </div> \n");
      out.write("                    \n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                    \n");
      out.write("                    <!-- 2-3 베스트제품더보기 -->\n");
      out.write("                    <div>\n");
      out.write("                        <div class=\"more bestMore\">\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/bestProduct\">더보기 \n");
      out.write("                            		<i class=\"fa-solid fa-angles-right\" id=\"allow\"></i>\n");
      out.write("                            </a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                </section>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                <!-- 3 신제품부분 시작 -->\n");
      out.write("                <section class=\"newPart\">\n");
      out.write("\n");
      out.write("                    <!-- 3-1 신제품 글씨 -->\n");
      out.write("                    <div class=\"mainFont newFont\">신제품</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <!-- 3-2 신제품 순 -->\n");
      out.write("                    <div class=\"newItem\">\n");
      out.write("\n");
      out.write("                        <!-- 신제품1 -->\n");
      out.write("                        <div class=\"BNitem Nitem1\">\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <div class=\"BNitemPic newItem1Pic\">\n");
      out.write("                                    <figcaption>신제품1<br><br> 상세설명칸<br><br> 입니다 </figcaption>\n");
      out.write("                                    <img src=\"resources/image/index/제품_오쏘뮬.jpg\" \n");
      out.write("                                        alt=\"제품사진\" id=\"newItemPhoto1\">  \n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("                                <div class=\"BNitemName newItem1Name\">\n");
      out.write("                                    <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a> \n");
      out.write("                                </div>\n");
      out.write("                           \n");
      out.write("                                <div class=\"BNitemPrice newItem1Price\">65,000원</div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <!-- 신제품2 -->\n");
      out.write("                        <div class=\"BNitem Nitem2\">\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <div class=\"BNitemPic newItem2Pic\">\n");
      out.write("                                    <figcaption>신제품2<br><br> 상세설명칸<br><br> 입니다 </figcaption>\n");
      out.write("                                    <img src=\"resources/image/index/제품_오쏘뮬.jpg\" \n");
      out.write("                                        alt=\"제품사진\" id=\"newItemPhoto2\">\n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("                                <div class=\"BNitemName newItem2Name\">\n");
      out.write("                                    <a href=\"#\">신제품2 설명</a>\n");
      out.write("                                </div>\n");
      out.write("                            \n");
      out.write("                                <div class=\"BNitemPrice newItem2Price\">신제품2 가격</div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <!-- 신제품3 -->\n");
      out.write("                        <div class=\"BNitem Nitem3\">\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <div class=\"BNitemPic newItem3Pic\">\n");
      out.write("                                    <figcaption>신제품3<br><br> 상세설명칸<br><br> 입니다 </figcaption>\n");
      out.write("                                    <img src=\"resources/image/index/제품_오쏘뮬.jpg\" \n");
      out.write("                                        alt=\"제품사진\" id=\"newItemPhoto3\">\n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("                                <div class=\"BNitemName newItem3Name\">\n");
      out.write("                                    <a href=\"#\">신제품3 설명</a>\n");
      out.write("                                </div>\n");
      out.write("\n");
      out.write("                                <div class=\"BNitemPrice newItem3Price\">신제품3 가격</div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <!-- 신제품4 -->\n");
      out.write("                        <div class=\"BNitem Nitem4\">\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <div class=\"BNitemPic newItem4Pic\">\n");
      out.write("                                    <figcaption>신제품4<br><br> 상세설명칸<br><br> 입니다 </figcaption>\n");
      out.write("                                    <img src=\"resources/image/index/제품_오쏘뮬.jpg\" \n");
      out.write("                                        alt=\"제품사진\" id=\"newItemPhoto4\">\n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("                                <div class=\"BNitemName newItem4Name\">\n");
      out.write("                                    <a href=\"#\">신제품4 설명</a>\n");
      out.write("                                </div>\n");
      out.write("                              \n");
      out.write("                                <div class=\"BNitemPrice newItem4Price\">신제품4 가격</div>\n");
      out.write("                        </div>\n");
      out.write("                    \n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <!-- 3-3 신제품 더보기 -->\n");
      out.write("                    <div>\n");
      out.write("                        <div class=\"more newMore\">\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/newProduct\">더보기 <i class=\"fa-solid fa-angles-right\" id=\"allow\"></i></a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                <!-- 신제품부분 끝  -->\n");
      out.write("                </section>\n");
      out.write("            \n");
      out.write("\n");
      out.write("                \n");
      out.write("                \n");
      out.write("                <!-- 4 제품부분 시작 -->\n");
      out.write("                <section class=\"itemPart\">\n");
      out.write("\n");
      out.write("                    <!-- 4-1 제품글씨 -->\n");
      out.write("                    <div class=\"mainFont itemFont\">제품</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <!-- 4-2 제품모음 -->\n");
      out.write("                    <div class=\"itemGather\">\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <!-- 제품 1 ~3 -->\n");
      out.write("                        <div class=\"itemFirst\">\n");
      out.write("\n");
      out.write("\n");
      out.write("                            <!-- 제품1 -->\n");
      out.write("                            <div class=\"item item1\">\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    <div class=\"itemPic item1Pic\">\n");
      out.write("                                        <figcaption>제품1<br><br>상세설명칸<br><br>입니다</figcaption>\n");
      out.write("                                        <img src=\"resources/image/index/제품_오쏘뮬.jpg\" \n");
      out.write("                                            alt=\"이미지입니다\" id=\"itemPhoto1\">\n");
      out.write("                                    </div>\n");
      out.write("                                </a>\n");
      out.write("                                \n");
      out.write("                                    <div class=\"itemName item1Name\">\n");
      out.write("                                        <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>\n");
      out.write("                                    </div>\n");
      out.write("\n");
      out.write("                                    <div class=\"itemPrice item1Price\">16,000원</div>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                            <!-- 제품2 -->\n");
      out.write("                            <div class=\"item item2\">\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    <div class=\"itemPic item2Pic\">\n");
      out.write("                                        <figcaption>제품2<br><br>상세설명칸<br><br>입니다</figcaption>\n");
      out.write("                                        <img src=\"resources/image/index/제품_오쏘뮬.jpg\" \n");
      out.write("                                            alt=\"이미지입니다\" id=\"itemPhoto2\">\n");
      out.write("                                    </div>\n");
      out.write("                                </a>    \n");
      out.write("\n");
      out.write("                                    <div class=\"itemName item2Name\">\n");
      out.write("                                        <a href=\"\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>\n");
      out.write("                                    </div>\n");
      out.write("\n");
      out.write("                                    <div class=\"itemPrice item2Price\">16,000원</div>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                            <!-- 제품3 -->\n");
      out.write("                            <div class=\"item item3\">\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    <div class=\"itemPic item3Pic\">\n");
      out.write("                                        <figcaption>제품3<br><br>상세설명칸<br><br>입니다</figcaption>\n");
      out.write("                                        <img src=\"resources/image/index/제품_오쏘뮬.jpg\" \n");
      out.write("                                            alt=\"이미지입니다\" id=\"itemPhoto3\">\n");
      out.write("                                    </div>\n");
      out.write("                                </a>\n");
      out.write("                               \n");
      out.write("\n");
      out.write("                                    <div class=\"itemName item3Name\">\n");
      out.write("                                        <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>\n");
      out.write("                                    </div>\n");
      out.write("\n");
      out.write("                                    <div class=\"itemPrice item3Price\">16,000원</div>\n");
      out.write("                            </div>\n");
      out.write("                        \n");
      out.write("                        \n");
      out.write("                        </div>\n");
      out.write("                    \n");
      out.write("\n");
      out.write("\n");
      out.write("                        <!-- 제품 4~6 -->\n");
      out.write("                        <div class=\"itemSecond\">\n");
      out.write("\n");
      out.write("\n");
      out.write("                            <!-- 제품4 -->\n");
      out.write("                            <div class=\"item item4\">\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    <div class=\"itemPic item4Pic\">\n");
      out.write("                                        <figcaption>제품4<br><br>상세설명칸<br><br>입니다</figcaption>\n");
      out.write("                                        <img src=\"resources/image/index/제품_오쏘뮬.jpg\" \n");
      out.write("                                            alt=\"이미지입니다\" id=\"itemPhoto4\"> \n");
      out.write("                                    </div>\n");
      out.write("                                </a>\n");
      out.write("\n");
      out.write("                                    <div class=\"itemName item4Name\">\n");
      out.write("                                        <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>\n");
      out.write("                                    </div>\n");
      out.write("\n");
      out.write("                                    <div class=\"itemPrice item4Price\">16,000원</div>    \n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                            <!-- 제품5 -->\n");
      out.write("                            <div class=\"item item5\">\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    <div class=\"itemPic item5Pic\">\n");
      out.write("                                        <figcaption>제품5<br><br>상세설명칸<br><br>입니다</figcaption>\n");
      out.write("                                        <img src=\"resources/image/index/제품_오쏘뮬.jpg\"  \n");
      out.write("                                            alt=\"이미지입니다\" id=\"itemPhoto5\">   \n");
      out.write("                                    </div>\n");
      out.write("                                </a>\n");
      out.write("\n");
      out.write("                                    <div class=\"itemName item5Name\">\n");
      out.write("                                        <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>\n");
      out.write("                                    </div>\n");
      out.write("\n");
      out.write("                                    <div class=\"itemPrice item5Price\">16,000원</div>  \n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                            <!-- 제품6 -->\n");
      out.write("                            <div class=\"item item6\">\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    <div class=\"itemPic item6Pic\">\n");
      out.write("                                        <figcaption>제품6<br><br>상세설명칸<br><br>입니다</figcaption>\n");
      out.write("                                        <img src=\"resources/image/index/제품_오쏘뮬.jpg\"  \n");
      out.write("                                            alt=\"이미지입니다\" id=\"itemPhoto6\">\n");
      out.write("                                    </div>\n");
      out.write("                                </a>\n");
      out.write("\n");
      out.write("                                    <div class=\"itemName item6Name\">\n");
      out.write("                                        <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>\n");
      out.write("                                    </div>\n");
      out.write("\n");
      out.write("                                    <div class=\"itemPrice item6Price\">16,000원</div> \n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                        \n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <!-- 제품7~9 -->\n");
      out.write("                        <div class=\"itemThird\">\n");
      out.write("\n");
      out.write("\n");
      out.write("                            <!-- 제품7 -->\n");
      out.write("                            <div class=\"item item7\">\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    <div class=\"itemPic item7Pic\">\n");
      out.write("                                        <figcaption>제품7<br><br>상세설명칸<br><br>입니다</figcaption>\n");
      out.write("                                        <img src=\"resources/image/index/제품_오쏘뮬.jpg\"  \n");
      out.write("                                            alt=\"이미지입니다\" id=\"itemPhoto7\">\n");
      out.write("                                    </div>\n");
      out.write("                                </a>\n");
      out.write("                                \n");
      out.write("                                    <div class=\"itemName item7Name\">\n");
      out.write("                                        <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>\n");
      out.write("                                    </div>\n");
      out.write("\n");
      out.write("                                    <div class=\"itemPrice item7Price\">16,000원</div>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                            <!-- 제품8 -->\n");
      out.write("                            <div class=\"item item8\">\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    <div class=\"itemPic item8Pic\">\n");
      out.write("                                        <figcaption>제품8<br><br>상세설명칸<br><br>입니다</figcaption>\n");
      out.write("                                        <img src=\"resources/image/index/제품_오쏘뮬.jpg\" \n");
      out.write("                                            alt=\"이미지입니다\" id=\"itemPhoto8\">\n");
      out.write("                                    </div>\n");
      out.write("                                </a>\n");
      out.write("\n");
      out.write("                                    <div class=\"itemName item8Name\">\n");
      out.write("                                        <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>\n");
      out.write("                                    </div>\n");
      out.write("\n");
      out.write("                                    <div class=\"itemPrice item8Price\">16,000원</div> \n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                            <!-- 제품9 -->\n");
      out.write("                            <div class=\"item item9\">\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    <div class=\"itemPic item9Pic\">\n");
      out.write("                                        <figcaption>제품8<br><br>상세설명칸<br><br>입니다</figcaption>\n");
      out.write("                                        <img src=\"resources/image/index/제품_오쏘뮬.jpg\" \n");
      out.write("                                            alt=\"이미지입니다\" id=\"itemPhoto9\">\n");
      out.write("                                    </div>\n");
      out.write("                                </a>\n");
      out.write("\n");
      out.write("                                    <div class=\"itemName item9Name\">\n");
      out.write("                                        <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>\n");
      out.write("                                    </div>\n");
      out.write("\n");
      out.write("                                    <div class=\"itemPrice item9Price\">16,000원</div> \n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                \n");
      out.write("                    <!-- 4-3 제품더보기 더보기 -->\n");
      out.write("                    <div class=\"itemMore\"> \n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/allProduct\">더보기 <i class=\"fa-solid fa-angles-right\" id=\"allow\"> </i></a>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                <!-- 제품부분 끝 -->\n");
      out.write("                </section>\n");
      out.write("            \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("            <!-- 가운데페이지 끝 -->\n");
      out.write("            </section>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("            <!-- 오른쪽사이드바 -->\n");
      out.write("            <section class=\"rightSide\">\n");
      out.write("\n");
      out.write("\n");
      out.write("                 <!-- 인체사진 플로팅바-->\n");
      out.write("                 <div class=\"floating\" id=\"floating\">\n");
      out.write("                    <a href=\"product/person\">\n");
      out.write("                        <img id=\"people\" src=\"resources/image/index/인체이미지누끼.png\" >\n");
      out.write("                        <img id=\"people2\" src=\"resources/image/index/인체이미지누끼2.png\" >\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("            \n");
      out.write("            </section>\n");
      out.write("\n");
      out.write("        </section>\n");
      out.write("        <!-- content 전체 감싸는 영역 끝 -->\n");
      out.write("\n");
      out.write("       \n");
      out.write("    <!-- 헤더, 컨텐츠 끝 -->\n");
      out.write("    </main>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- 푸터 -->\n");
      out.write("  	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("	<!-- jQuery 라이브러리 추가 -->\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\" integrity=\"sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=\" crossorigin=\"anonymous\"></script>\n");
      out.write(" \n");
      out.write("    <!-- main.js 연결 -->\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/index.js\"></script>\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/main.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("=======\n");
      out.write("\n");
      out.write(">>>>>>> develop\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
