/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-04-06 05:14:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class faq_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1680738812000L));
    _jspx_dependants.put("jar:file:/Users/deokkeun/Desktop/YoSangSo-main/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/yosangso/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/main-style.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/faq.css\">\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("    <script src=\"https://kit.fontawesome.com/881d1deef7.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("    <title>FAQ</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <!-- 헤더, 컨텐츠 -->\n");
      out.write("    <main>\n");
      out.write("        \n");
      out.write("        <!-- 헤더 -->\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\n");
      out.write("        \n");
      out.write("        \n");
      out.write("       \n");
      out.write("       \n");
      out.write("        <div class=\"header-main\">\n");
      out.write("            <div id=\"faq-title-head\">자주 묻는 질문</div>\n");
      out.write("            <div id=\"faq-subtitle-head\">요생소에 자주 묻는 질문입니다.</div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"main-div\">\n");
      out.write("            <!-- tap메뉴 -->\n");
      out.write("            <div class=\"tab-menu\">\n");
      out.write("                <ul class=\"tap-list\">\n");
      out.write("                    <li class=\"tap-link current\" data-tab=\"tab-tab1\">전체</li>\n");
      out.write("                    <li class=\"tap-link\" data-tab=\"tab-tab2\">제품</li>\n");
      out.write("                    <li class=\"tap-link\" data-tab=\"tab-tab3\">회원관리</li>\n");
      out.write("                    <li class=\"tap-link\" data-tab=\"tab-tab4\">주문/결제</li>\n");
      out.write("                    <li class=\"tap-link\" data-tab=\"tab-tab5\">취소/환불</li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("            <!-- 카테코리 -->\n");
      out.write("            <div class=\"category-name\">\n");
      out.write("                <div>분류</div>\n");
      out.write("                <div>제목</div>\n");
      out.write("            </div>\n");
      out.write("            <!-- 메인 컨텐츠 -->\n");
      out.write("            <div class=\"main-faq-menu\">\n");
      out.write("                <div class=\"faq-contents current\" id=\"tab-tab1\">\n");
      out.write("                    <div class=\"accordion accordion-flush\" id=\"accordionFlushExample\">\n");
      out.write("                        <div class=\"accordion-item\">\n");
      out.write("                        <h2 class=\"accordion-header\" id=\"flush-headingOne\">\n");
      out.write("                            <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseOne\" aria-controls=\"flush-collapseOne\">\n");
      out.write("                                <div class=\"button-con\">\n");
      out.write("                                    <div>회원관리</div>\n");
      out.write("                                    <div>회원 탈퇴를 하고 싶어요.</div>\n");
      out.write("                                </div>\n");
      out.write("                            </button>\n");
      out.write("                        </h2>\n");
      out.write("                        <div id=\"flush-collapseOne\" class=\"accordion-collapse collapse\" aria-labelledby=\"flush-headingOne\" data-bs-parent=\"#accordionFlushExample\">\n");
      out.write("                            <div class=\"accordion-body\">회원 탈퇴를 원하시나요? <br>\n");
      out.write("                            회원 탈퇴는 홈페이지 -> 마이페이지 -> 회원탈퇴에서 탈퇴하실 수 있어요.\n");
      out.write("                            <br> 개선 사항을 알려주시면 반영하겠습니다. 감사합니다.\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"accordion-item\">\n");
      out.write("                        <h2 class=\"accordion-header\" id=\"flush-headingTwo\">\n");
      out.write("                            <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseTwo\" aria-expanded=\"false\" aria-controls=\"flush-collapseTwo\">\n");
      out.write("                            <div class=\"button-con\">\n");
      out.write("                                <div>회원관리</div>\n");
      out.write("                                <div>회원 정보를 변경하고 싶어요.</div>\n");
      out.write("                            </div>\n");
      out.write("                            </button>\n");
      out.write("                        </h2>\n");
      out.write("                        <div id=\"flush-collapseTwo\" class=\"accordion-collapse collapse\" aria-labelledby=\"flush-headingTwo\" data-bs-parent=\"#accordionFlushExample\">\n");
      out.write("                            <div class=\"accordion-body\">회원 정보는 홈페이지 -> 마이페이지에서 변경 가능합니다. 감사합니다.</div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"accordion-item\">\n");
      out.write("                            <h2 class=\"accordion-header\" id=\"flush-headingThree\">\n");
      out.write("                            <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseThree\" aria-expanded=\"false\" aria-controls=\"flush-collapseThree\">\n");
      out.write("                                <div class=\"button-con\">\n");
      out.write("                                <div>회원관리</div>\n");
      out.write("                                <div>비밀번호가 기억나지 않아요</div>\n");
      out.write("                            </div>\n");
      out.write("                            </button>\n");
      out.write("                            </h2>\n");
      out.write("                            <div id=\"flush-collapseThree\" class=\"accordion-collapse collapse\" aria-labelledby=\"flush-headingThree\" data-bs-parent=\"#accordionFlushExample\">\n");
      out.write("                            <div class=\"accordion-body\">비밀번호는 로그인 창의 아이디/비밀번호 찾기에서 찾을 수 있습니다. <br>\n");
      out.write("                            만일 진행이 원할하게 되지 않을 시 요생소 고객센터에 전화를 주시면 친절하게 도와드리겠습니다.</div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"accordion-item\">\n");
      out.write("                        <h2 class=\"accordion-header\" id=\"flush-headingFour\">\n");
      out.write("                            <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseFour\" aria-expanded=\"false\" aria-controls=\"flush-collapseFour\">\n");
      out.write("                                <div class=\"button-con\">\n");
      out.write("                                    <div>제품</div>\n");
      out.write("                                    <div>요생소 제품은 믿을만한가요?</div>\n");
      out.write("                                </div>\n");
      out.write("                            </button>\n");
      out.write("                        </h2>\n");
      out.write("                        <div id=\"flush-collapseFour\" class=\"accordion-collapse collapse\" aria-labelledby=\"flush-headingFour\" data-bs-parent=\"#accordionFlushExample\">\n");
      out.write("                            <div class=\"accordion-body\">요생소 제품은 모두 식약처 인증을 받은 제품입니다. <br>\n");
      out.write("                            충분한 임상을 거친 제품만을 판매하고 있으니 안심하시고 드셔도 됩니다.\n");
      out.write("                            <br> 추가 문의 사항이 있으면 개인 문의를 이용해주시면 감사하겠습니다.\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"accordion-item\">\n");
      out.write("                        <h2 class=\"accordion-header\" id=\"flush-headingFive\">\n");
      out.write("                            <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseFive\" aria-expanded=\"false\" aria-controls=\"flush-collapseFive\">\n");
      out.write("                            <div class=\"button-con\">\n");
      out.write("                                <div>제품</div>\n");
      out.write("                                <div>알러지가 있는데 먹어도 되나요?</div>\n");
      out.write("                            </div>\n");
      out.write("                            </button>\n");
      out.write("                        </h2>\n");
      out.write("                        <div id=\"flush-collapseFive\" class=\"accordion-collapse collapse\" aria-labelledby=\"flush-headingFive\" data-bs-parent=\"#accordionFlushExample\">\n");
      out.write("                            <div class=\"accordion-body\">특정 약품에 따른 알러지 반응을 모두 예상하기 어려워 전문의와 상담 후 섭취하시길 권하고 있습니다. <br>\n");
      out.write("                            혹시나 특정 성분에 대해 궁금한 점이 있으시면 1대1 문의를 통해 연락주시면<br>\n");
      out.write("                        친절하게 답변해드리겠습니다.</div>\n");
      out.write("                        </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"accordion-item\">\n");
      out.write("                        <h2 class=\"accordion-header\" id=\"flush-headingSix\">\n");
      out.write("                            <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseSix\" aria-controls=\"flush-collapseSix\">\n");
      out.write("                            <div class=\"button-con\">\n");
      out.write("                                <div>제품</div>\n");
      out.write("                                <div>손상된 제품이 왔습니다.</div>\n");
      out.write("                            </div>\n");
      out.write("                            </button>\n");
      out.write("                        </h2>\n");
      out.write("                        <div id=\"flush-collapseSix\" class=\"accordion-collapse collapse\" aria-labelledby=\"flush-headingSix\" data-bs-parent=\"#accordionFlushExample\">\n");
      out.write("                            <div class=\"accordion-body\">파손이나 불량 상품은 즉시 환불 또는 교환해드리고 있습니다. <br>\n");
      out.write("                            상세한 사진과 함께 환불 / 교환 접수를 해주시면 바로 도와드리겠습니다.\n");
      out.write("                        </div>\n");
      out.write("                        </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"accordion-item\">\n");
      out.write("                        <h2 class=\"accordion-header\" id=\"flush-headingSeven\">\n");
      out.write("                            <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseSeven\" aria-expanded=\"false\" aria-controls=\"flush-collapseSeven\">\n");
      out.write("                            <div class=\"button-con\">\n");
      out.write("                                <div>제품</div>\n");
      out.write("                                <div>다른 제품과 함께 복용해도 되나요?</div>\n");
      out.write("                            </div>\n");
      out.write("                            </button>\n");
      out.write("                        </h2>\n");
      out.write("                        <div id=\"flush-collapseSeven\" class=\"accordion-collapse collapse\" aria-labelledby=\"flush-headingSeven\" data-bs-parent=\"#accordionFlushExample\">\n");
      out.write("                            <div class=\"accordion-body\">요생소 비타민은 다른 제품과 같이 드셔도 문제가 없는 제품만을 판매하고 있습니다. <br>\n");
      out.write("                            다만 개개인의 체질과 병력에 따라 부작용이 있을 수 있으므로 의사와 상담 후에 드시길 권해드리고 있습니다.</div>\n");
      out.write("                        </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"accordion-item\">\n");
      out.write("                        <h2 class=\"accordion-header\" id=\"flush-headingeight\">\n");
      out.write("                            <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseeight\" aria-expanded=\"false\" aria-controls=\"flush-collapseeight\">\n");
      out.write("                            <div class=\"button-con\">\n");
      out.write("                                <div>주문/결제</div>\n");
      out.write("                                <div>결제 방법은 어떻게 되나요?</div>\n");
      out.write("                            </div>\n");
      out.write("                            </button>\n");
      out.write("                        </h2>\n");
      out.write("                        <div id=\"flush-collapseeight\" class=\"accordion-collapse collapse\" aria-labelledby=\"flush-headingOne\" data-bs-parent=\"#accordionFlushExample\">\n");
      out.write("                            <div class=\"accordion-body\">주문은 카카오페이를 지원하고 있습니다. \n");
      out.write("                            <br>추후에 다른 결제 방식을 추가할 예정입니다. 감사합니다.</div>\n");
      out.write("                        </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"accordion-item\">\n");
      out.write("                        <h2 class=\"accordion-header\" id=\"flush-headingnine\">\n");
      out.write("                            <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapsenine\"  aria-controls=\"flush-collapsenine\">\n");
      out.write("                            <div class=\"button-con\">\n");
      out.write("                                <div>주문/결제</div>\n");
      out.write("                                <div>정기 구독 결제가 가능한가요?</div>\n");
      out.write("                            </div>\n");
      out.write("                            </button>\n");
      out.write("                        </h2>\n");
      out.write("                        <div id=\"flush-collapsenine\" class=\"accordion-collapse collapse\" aria-labelledby=\"flush-headingnine\" data-bs-parent=\"#accordionFlushExample\">\n");
      out.write("                            <div class=\"accordion-body\">정기 결제를 통한 구독 방식은 아직 지원하지 않습니다. <br>\n");
      out.write("                            추후에 구독 상품을 마련해 안내해 드릴 예정입니다. 꾸준한 사랑과 관심 감사합니다.</div>\n");
      out.write("                        </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"accordion-item\">\n");
      out.write("                        <h2 class=\"accordion-header\" id=\"flush-headingTen\">\n");
      out.write("                            <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseTen\" aria-expanded=\"false\" aria-controls=\"flush-collapsethree4\">\n");
      out.write("                            <div class=\"button-con\">\n");
      out.write("                                <div>주문/결제</div>\n");
      out.write("                                <div>결제가 진행되지 않습니다. 도와주세요</div>\n");
      out.write("                            </div>\n");
      out.write("                            </button>\n");
      out.write("                        </h2>\n");
      out.write("                        <div id=\"flush-collapseTen\" class=\"accordion-collapse collapse\" aria-labelledby=\"flush-headingten\" data-bs-parent=\"#accordionFlushExample\">\n");
      out.write("                            <div class=\"accordion-body\">결제 오류는 다양한 상황이 있습니다. 정확한 오류 코드를 문의해주시면\n");
      out.write("                                <br>빠른 시일 내로 조치해드리겠습니다.\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"accordion-item\">\n");
      out.write("                            <h2 class=\"accordion-header\" id=\"flush-headingElev\">\n");
      out.write("                            <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseElev\" aria-expanded=\"false\" aria-controls=\"flush-collapseElev\">\n");
      out.write("                                <div class=\"button-con\">\n");
      out.write("                                <div>취소/환불</div>\n");
      out.write("                                <div>환불 신청은 어떻게 해야 하나요?</div>\n");
      out.write("                                </div>\n");
      out.write("                            </button>\n");
      out.write("                            </h2>\n");
      out.write("                            <div id=\"flush-collapseElev\" class=\"accordion-collapse collapse\" aria-labelledby=\"flush-headingOne\" data-bs-parent=\"#accordionFlushExample\">\n");
      out.write("                            <div class=\"accordion-body\">환불 신청은 마이페이지에서 주문한 상품 목록에서 신청하실 수 있습니다.<br>\n");
      out.write("                            </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"accordion-item\">\n");
      out.write("                            <h2 class=\"accordion-header\" id=\"flush-headingTwo5\">\n");
      out.write("                            <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseTwo5\"  aria-controls=\"flush-collapseTwo5\">\n");
      out.write("                                <div class=\"button-con\">\n");
      out.write("                                <div>취소/환불</div>\n");
      out.write("                                <div>환불한 금액은 언제 입금되나요?</div>\n");
      out.write("                            </div>\n");
      out.write("                            </button>\n");
      out.write("                            </h2>\n");
      out.write("                            <div id=\"flush-collapseTwo5\" class=\"accordion-collapse collapse\" aria-labelledby=\"flush-headingTwo\" data-bs-parent=\"#accordionFlushExample\">\n");
      out.write("                            <div class=\"accordion-body\">환불진행이 완료 되면 1~3일 내로 환불 금액이 입금됩니다. <br>\n");
      out.write("                            만일 진행이 원할하게 되지 않을 시 요생소 고객센터에 전화를 주시면 친절하게 도와드리겠습니다.</div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"accordion-item\">\n");
      out.write("                            <h2 class=\"accordion-header\" id=\"flush-headingthree5\">\n");
      out.write("                            <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapsethree5\" aria-expanded=\"false\" aria-controls=\"flush-collapsethree5\">\n");
      out.write("                                <div class=\"button-con\">\n");
      out.write("                                <div>취소/환불</div>\n");
      out.write("                                <div>환불 사유는 어떻게 되나요?</div>\n");
      out.write("                                </div>\n");
      out.write("                            </button>\n");
      out.write("                            </h2>\n");
      out.write("                            <div id=\"flush-collapsethree5\" class=\"accordion-collapse collapse\" aria-labelledby=\"flush-headingthree\" data-bs-parent=\"#accordionFlushExample\">\n");
      out.write("                            <div class=\"accordion-body\">요생소는 제품 이상이 아닌 단순 변심에 의한 환불 역시 진행하고 있습니다.<br>\n");
      out.write("                            다만 사용자의 사용 및 훼손이 있을 시 환불 불가능함을 알려드립니다.</div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <!-- tap2 -->\n");
      out.write("                <div class=\"faq-contents\" id=\"tab-tab2\">\n");
      out.write("                <div class=\"accordion accordion-flush\" id=\"accordionFlushExample2\">\n");
      out.write("                    <div class=\"accordion-item\">\n");
      out.write("                    <h2 class=\"accordion-header\" id=\"flush-headingOne2\">\n");
      out.write("                        <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseOne2\" aria-controls=\"flush-collapseOne2\">\n");
      out.write("                            <div class=\"button-con\">\n");
      out.write("                                <div>제품</div>\n");
      out.write("                                <div>요생소 제품은 믿을만한가요?</div>\n");
      out.write("                            </div>\n");
      out.write("                        </button>\n");
      out.write("                    </h2>\n");
      out.write("                    <div id=\"flush-collapseOne2\" class=\"accordion-collapse collapse\" aria-labelledby=\"flush-headingOne\" data-bs-parent=\"#accordionFlushExample2\">\n");
      out.write("                        <div class=\"accordion-body\">요생소 제품은 모두 식약처 인증을 받은 제품입니다. <br>\n");
      out.write("                        충분한 임상을 거친 제품만을 판매하고 있으니 안심하시고 드셔도 됩니다.\n");
      out.write("                        <br> 추가 문의 사항이 있으면 개인 문의를 이용해주시면 감사하겠습니다.\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"accordion-item\">\n");
      out.write("                    <h2 class=\"accordion-header\" id=\"flush-headingTwo2\">\n");
      out.write("                        <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseTwo2\" aria-expanded=\"false\" aria-controls=\"flush-collapseTwo2\">\n");
      out.write("                        <div class=\"button-con\">\n");
      out.write("                            <div>제품</div>\n");
      out.write("                            <div>알러지가 있는데 먹어도 되나요?</div>\n");
      out.write("                        </div>\n");
      out.write("                        </button>\n");
      out.write("                    </h2>\n");
      out.write("                    <div id=\"flush-collapseTwo2\" class=\"accordion-collapse collapse\" aria-labelledby=\"flush-headingTwo\" data-bs-parent=\"#accordionFlushExample2\">\n");
      out.write("                        <div class=\"accordion-body\">특정 약품에 따른 알러지 반응을 모두 예상하기 어려워 전문의와 상담 후 섭취하시길 권하고 있습니다. <br>\n");
      out.write("                        혹시나 특정 성분에 대해 궁금한 점이 있으시면 1대1 문의를 통해 연락주시면<br>\n");
      out.write("                    친절하게 답변해드리겠습니다.</div>\n");
      out.write("                    </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"accordion-item\">\n");
      out.write("                    <h2 class=\"accordion-header\" id=\"flush-headingThree2\">\n");
      out.write("                        <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseThree2\" aria-controls=\"flush-collapseThree2\">\n");
      out.write("                        <div class=\"button-con\">\n");
      out.write("                            <div>제품</div>\n");
      out.write("                            <div>손상된 제품이 왔습니다.</div>\n");
      out.write("                        </div>\n");
      out.write("                        </button>\n");
      out.write("                    </h2>\n");
      out.write("                    <div id=\"flush-collapseThree2\" class=\"accordion-collapse collapse\" aria-labelledby=\"flush-headingThree\" data-bs-parent=\"#accordionFlushExample2\">\n");
      out.write("                        <div class=\"accordion-body\">파손이나 불량 상품은 즉시 환불 또는 교환해드리고 있습니다. <br>\n");
      out.write("                        상세한 사진과 함께 환불 / 교환 접수를 해주시면 바로 도와드리겠습니다.\n");
      out.write("                    </div>\n");
      out.write("                    </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"accordion-item\">\n");
      out.write("                    <h2 class=\"accordion-header\" id=\"flush-headingFour2\">\n");
      out.write("                        <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseFour2\" aria-expanded=\"false\" aria-controls=\"flush-collapseFour2\">\n");
      out.write("                        <div class=\"button-con\">\n");
      out.write("                            <div>제품</div>\n");
      out.write("                            <div>다른 제품과 함께 복용해도 되나요?</div>\n");
      out.write("                        </div>\n");
      out.write("                        </button>\n");
      out.write("                    </h2>\n");
      out.write("                    <div id=\"flush-collapseFour2\" class=\"accordion-collapse collapse\" aria-labelledby=\"flush-headingFouor\" data-bs-parent=\"#accordionFlushExample2\">\n");
      out.write("                        <div class=\"accordion-body\">요생소 비타민은 다른 제품과 같이 드셔도 문제가 없는 제품만을 판매하고 있습니다. <br>\n");
      out.write("                        다만 개개인의 체질과 병력에 따라 부작용이 있을 수 있으므로 의사와 상담 후에 드시길 권해드리고 있습니다.</div>\n");
      out.write("                    </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                </div>\n");
      out.write("                <!-- tab3 -->\n");
      out.write("                <div class=\"faq-contents\" id=\"tab-tab3\">\n");
      out.write("                <div class=\"accordion accordion-flush\" id=\"accordionFlushExample3\">\n");
      out.write("                    <div class=\"accordion-item\">\n");
      out.write("                    <h2 class=\"accordion-header\" id=\"flush-headingOne3\">\n");
      out.write("                        <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseOne3\" aria-controls=\"flush-collapseOne\">\n");
      out.write("                            <div class=\"button-con\">\n");
      out.write("                                <div>회원관리</div>\n");
      out.write("                                <div>회원 탈퇴를 하고 싶어요.</div>\n");
      out.write("                            </div>\n");
      out.write("                        </button>\n");
      out.write("                    </h2>\n");
      out.write("                    <div id=\"flush-collapseOne3\" class=\"accordion-collapse collapse\" aria-labelledby=\"flush-headingOne\" data-bs-parent=\"#accordionFlushExample3\">\n");
      out.write("                        <div class=\"accordion-body\">회원 탈퇴를 원하시나요? <br>\n");
      out.write("                        회원 탈퇴는 홈페이지 -> 마이페이지 -> 회원탈퇴에서 탈퇴하실 수 있어요.\n");
      out.write("                        <br> 개선 사항을 알려주시면 반영하겠습니다. 감사합니다.\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"accordion-item\">\n");
      out.write("                    <h2 class=\"accordion-header\" id=\"flush-headingTwo3\">\n");
      out.write("                        <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseTwo3\" aria-expanded=\"false\" aria-controls=\"flush-collapseTwo\">\n");
      out.write("                        <div class=\"button-con\">\n");
      out.write("                            <div>회원관리</div>\n");
      out.write("                            <div>회원 정보를 변경하고 싶어요.</div>\n");
      out.write("                        </div>\n");
      out.write("                        </button>\n");
      out.write("                    </h2>\n");
      out.write("                    <div id=\"flush-collapseTwo3\" class=\"accordion-collapse collapse\" aria-labelledby=\"flush-headingTwo\" data-bs-parent=\"#accordionFlushExample3\">\n");
      out.write("                        <div class=\"accordion-body\">회원 정보는 홈페이지 -> 마이페이지에서 변경 가능합니다. 감사합니다.</div>\n");
      out.write("                    </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"accordion-item\">\n");
      out.write("                    <h2 class=\"accordion-header\" id=\"flush-headingThree3\">\n");
      out.write("                        <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseThree3\" aria-expanded=\"false\" aria-controls=\"flush-collapseThree\">\n");
      out.write("                        <div class=\"button-con\">\n");
      out.write("                            <div>회원관리</div>\n");
      out.write("                            <div>비밀번호가 기억나지 않아요</div>\n");
      out.write("                        </div>\n");
      out.write("                        </button>\n");
      out.write("                    </h2>\n");
      out.write("                    <div id=\"flush-collapseThree3\" class=\"accordion-collapse collapse\" aria-labelledby=\"flush-headingThree\" data-bs-parent=\"#accordionFlushExample3\">\n");
      out.write("                        <div class=\"accordion-body\">비밀번호는 로그인 창의 아이디/비밀번호 찾기에서 찾을 수 있습니다. <br>\n");
      out.write("                        만일 진행이 원할하게 되지 않을 시 요생소 고객센터에 전화를 주시면 친절하게 도와드리겠습니다.</div>\n");
      out.write("                    </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                </div>\n");
      out.write("                <!-- tap4 -->\n");
      out.write("                <div class=\"faq-contents\" id=\"tab-tab4\">\n");
      out.write("                <div class=\"accordion accordion-flush\" id=\"accordionFlushExample4\">\n");
      out.write("                    <div class=\"accordion-item\">\n");
      out.write("                    <h2 class=\"accordion-header\" id=\"flush-headingOne4\">\n");
      out.write("                        <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseOne4\" aria-expanded=\"false\" aria-controls=\"flush-collapseOne4\">\n");
      out.write("                        <div class=\"button-con\">\n");
      out.write("                            <div>주문/결제</div>\n");
      out.write("                            <div>결제 방법은 어떻게 되나요?.</div>\n");
      out.write("                        </div>\n");
      out.write("                        </button>\n");
      out.write("                    </h2>\n");
      out.write("                    <div id=\"flush-collapseOne4\" class=\"accordion-collapse collapse\" aria-labelledby=\"flush-headingOne\" data-bs-parent=\"#accordionFlushExample4\">\n");
      out.write("                        <div class=\"accordion-body\">주문은 카카오페이를 지원하고 있습니다. \n");
      out.write("                        <br>추후에 다른 결제 방식을 추가할 예정입니다. 감사합니다.\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"accordion-item\">\n");
      out.write("                    <h2 class=\"accordion-header\" id=\"flush-headingTwo4\">\n");
      out.write("                        <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseTwo4\"  aria-controls=\"flush-collapseTwo4\">\n");
      out.write("                        <div class=\"button-con\">\n");
      out.write("                            <div>주문/결제</div>\n");
      out.write("                            <div>정기 구독 결제가 가능한가요?</div>\n");
      out.write("                        </div>\n");
      out.write("                        </button>\n");
      out.write("                    </h2>\n");
      out.write("                    <div id=\"flush-collapseTwo4\" class=\"accordion-collapse collapse\" aria-labelledby=\"flush-headingTwo\" data-bs-parent=\"#accordionFlushExample4\">\n");
      out.write("                        <div class=\"accordion-body\">정기 결제를 통한 구독 방식은 아직 지원하지 않습니다. <br>\n");
      out.write("                            추후에 구독 상품을 마련해 안내해 드릴 예정입니다. 꾸준한 사랑과 관심 감사합니다.</div>\n");
      out.write("                    </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"accordion-item\">\n");
      out.write("                    <h2 class=\"accordion-header\" id=\"flush-headingthree4\">\n");
      out.write("                        <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapsethree4\" aria-expanded=\"false\" aria-controls=\"flush-collapsethree4\">\n");
      out.write("                        <div class=\"button-con\">\n");
      out.write("                            <div>주문/결제</div>\n");
      out.write("                            <div>결제가 진행되지 않습니다. 도와주세요</div>\n");
      out.write("                        </div>\n");
      out.write("                        </button>\n");
      out.write("                    </h2>\n");
      out.write("                    <div id=\"flush-collapsethree4\" class=\"accordion-collapse collapse\" aria-labelledby=\"flush-headingthree\" data-bs-parent=\"#accordionFlushExample4\">\n");
      out.write("                        <div class=\"accordion-body\">결제 오류는 다양한 상황이 있습니다. 정확한 오류 코드를 문의해주시면\n");
      out.write("                            <br>빠른 시일 내로 조치해드리겠습니다.</div>\n");
      out.write("                    </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                </div>\n");
      out.write("                <!-- tap5 -->\n");
      out.write("                <div class=\"faq-contents\" id=\"tab-tab5\">\n");
      out.write("                    <div class=\"accordion accordion-flush\" id=\"accordionFlushExample11\">\n");
      out.write("                    <div class=\"accordion-item\">\n");
      out.write("                        <h2 class=\"accordion-header\" id=\"flush-headingT1\">\n");
      out.write("                        <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseT1\" aria-expanded=\"false\" aria-controls=\"flush-collapseTwelv\">\n");
      out.write("                            <div class=\"button-con\">\n");
      out.write("                            <div>취소/환불</div>\n");
      out.write("                            <div>환불 신청은 어떻게 해야 하나요?</div>\n");
      out.write("                            </div>\n");
      out.write("                        </button>\n");
      out.write("                        </h2>\n");
      out.write("                        <div id=\"flush-collapseT1\" class=\"accordion-collapse collapse\" aria-labelledby=\"flush-headingT1\" data-bs-parent=\"#accordionFlushExample11\">\n");
      out.write("                        <div class=\"accordion-body\">환불 신청은 마이페이지에서 주문한 상품 목록에서 신청하실 수 있습니다.<br>\n");
      out.write("                        </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"accordion-item\">\n");
      out.write("                        <h2 class=\"accordion-header\" id=\"flush-headingT2\">\n");
      out.write("                        <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseT2\"  aria-controls=\"flush-collapseTwo\">\n");
      out.write("                            <div class=\"button-con\">\n");
      out.write("                            <div>취소/환불</div>\n");
      out.write("                            <div>환불한 금액은 언제 입금되나요?</div>\n");
      out.write("                        </div>\n");
      out.write("                        </button>\n");
      out.write("                        </h2>\n");
      out.write("                        <div id=\"flush-collapseT2\" class=\"accordion-collapse collapse\" aria-labelledby=\"flush-headingT2\" data-bs-parent=\"#accordionFlushExample11\">\n");
      out.write("                        <div class=\"accordion-body\">환불진행이 완료 되면 1~3일 내로 환불 금액이 입금됩니다. <br>\n");
      out.write("                        만일 진행이 원할하게 되지 않을 시 요생소 고객센터에 전화를 주시면 친절하게 도와드리겠습니다.</div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"accordion-item\">\n");
      out.write("                        <h2 class=\"accordion-header\" id=\"flush-headingT3\">\n");
      out.write("                        <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseT3\" aria-expanded=\"false\" aria-controls=\"flush-collapsethree5\">\n");
      out.write("                            <div class=\"button-con\">\n");
      out.write("                            <div>취소/환불</div>\n");
      out.write("                            <div>환불 사유는 어떻게 되나요?</div>\n");
      out.write("                            </div>\n");
      out.write("                        </button>\n");
      out.write("                        </h2>\n");
      out.write("                        <div id=\"flush-collapseT3\" class=\"accordion-collapse collapse\" aria-labelledby=\"flush-headingT3\" data-bs-parent=\"#accordionFlushExample11\">\n");
      out.write("                        <div class=\"accordion-body\">요생소는 제품 이상이 아닌 단순 변심에 의한 환불 역시 진행하고 있습니다.<br>\n");
      out.write("                        다만 사용자의 사용 및 훼손이 있을 시 환불 불가능함을 알려드립니다.</div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("    <!-- 헤더, 컨텐츠 끝 -->\n");
      out.write("    </main>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- 푸터 -->\n");
      out.write("  	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("	<!-- jQuery 라이브러리 추가 -->\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\" integrity=\"sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=\" crossorigin=\"anonymous\"></script>\n");
      out.write("   \n");
      out.write("    <!-- main.js 연결 -->\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4\" crossorigin=\"anonymous\"></script>\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/main.js\"></script>\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/faq.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
