/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-04-06 01:35:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bestProduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1680738812000L));
    _jspx_dependants.put("jar:file:/Users/deokkeun/Desktop/YoSangSo-main/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/yosangso/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <!-- 헤더/풋터 css -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/main-style.css\">\n");
      out.write("    <script src=\"https://kit.fontawesome.com/881d1deef7.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("     <!-- 제품리스트 css -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/product/bestProduct.css\">\n");
      out.write("    <script src=\"https://kit.fontawesome.com/881d1deef7.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("    <title>bestProduct</title>\n");
      out.write("    \n");
      out.write("     <!--탑 버튼-->\n");
      out.write("    <a id=\"topBtn\" href=\"#\"> \n");
      out.write("        <i class=\"fa-solid fa-angles-up fa-2x\"></i>\n");
      out.write("    </a> \n");
      out.write("    \n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <!-- 헤더, 컨텐츠 -->\n");
      out.write("    <main>\n");
      out.write("        \n");
      out.write("        <!-- 헤더 -->\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\n");
      out.write("        \n");
      out.write("     \n");
      out.write("       \n");
      out.write("        <!--  <div>bestProduct</div> -->\n");
      out.write("\n");
      out.write("\n");
      out.write("		 <!-- 내용 작성 공간입니다.(template2) -->\n");
      out.write("         <!-- content 전체 감싸는 영역 -->\n");
      out.write("        <section class=\"content-container\">\n");
      out.write("\n");
      out.write("            <!-- 1. 왼쪽사이드 -->\n");
      out.write("            <section class=\"leftSide\">\n");
      out.write("            </section>\n");
      out.write("\n");
      out.write("\n");
      out.write("            <!-- 2. 가운데페이지 -->\n");
      out.write("            <section class=\"center\">\n");
      out.write("\n");
      out.write("\n");
      out.write("                <!-- 2-1 퀵메뉴 부분 -->\n");
      out.write("                <div class=\"quickMenu\">\n");
      out.write("\n");
      out.write("                    <!-- 2-1 글씨칸 --> \n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/allProduct\">\n");
      out.write("                    	<div class=\"mainFont allItemFont\">전제품</div>\n");
      out.write("                    </a>\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/newProduct\">\n");
      out.write("                    	<div class=\"mainFont newItemFont\">신상품</div>\n");
      out.write("                    </a>\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/bestProduct\">\n");
      out.write("                    	<div class=\"mainFont bestItemFont\">베스트</div>\n");
      out.write("                    </a>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                \n");
      out.write("\n");
      out.write("                <!-- 2-2 제품 목록 -->\n");
      out.write("                <div class=\"bestItem\">\n");
      out.write("                    \n");
      out.write("                    <!-- 1행 -->\n");
      out.write("                    <div class=\"line row1\">\n");
      out.write("                        <!--제품1-1 -->\n");
      out.write("                        <div class=\"BNitem Bitem1\">\n");
      out.write("                        	<p class=rank>1위</p>    \n");
      out.write("                            <a href=\"#\">    \n");
      out.write("                                <div class=\"BNitemPic bestItem1Pic\">\n");
      out.write("                                    <figcaption>제품1<br><br> 상세설명칸<br><br> 입니다 </figcaption>\n");
      out.write("                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/index/제품_나우푸드c1000.jpg\" \n");
      out.write("                                        alt=\"제품사진\" id=\"bestItemPhoto1\">\n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("                                <div class=\"BNitemName bestItem1Name\">\n");
      out.write("                                    <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>  \n");
      out.write("                                </div> \n");
      out.write("                            \n");
      out.write("                                <div class=\"BNitemPrice bestItem1Price\">75,000원</div>  \n");
      out.write("                        </div>                        \n");
      out.write("\n");
      out.write("                                                    \n");
      out.write("                        <!--제품1-2 -->\n");
      out.write("                        <div class=\"BNitem Bitem2\">\n");
      out.write("                        	<p class=rank>2위</p>    \n");
      out.write("                            <a href=\"#\">    \n");
      out.write("                                <div class=\"BNitemPic bestItem2Pic\">\n");
      out.write("                                    <figcaption>제품2<br><br> 상세설명칸<br><br> 입니다 </figcaption>\n");
      out.write("                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/index/제품_나우푸드c1000.jpg\" \n");
      out.write("                                        alt=\"제품사진\" id=\"bestItemPhoto1\">\n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("                                <div class=\"BNitemName bestItem2Name\">\n");
      out.write("                                    <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>  \n");
      out.write("                                </div> \n");
      out.write("                            \n");
      out.write("                                <div class=\"BNitemPrice bestItem2Price\">75,000원</div>  \n");
      out.write("                        </div>                          \n");
      out.write("\n");
      out.write("                        <!-- 제품1-3 -->\n");
      out.write("                        <div class=\"BNitem Bitem3\">\n");
      out.write("                        	<p class=rank>3위</p>    \n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <div class=\"BNitemPic bestItem3Pic\">\n");
      out.write("                                    <figcaption>제품3<br><br> 상세설명칸<br><br> 입니다 </figcaption>\n");
      out.write("                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/index/제품_나우푸드c1000.jpg\" \n");
      out.write("                                    alt=\"제품사진\" id=\"bestItemPhoto3\">\n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("\n");
      out.write("                                <div class=\"BNitemName bestItem3Name\">\n");
      out.write("                                    <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>  \n");
      out.write("                                </div>\n");
      out.write("\n");
      out.write("                                <div class=\"BNitemPrice bestItem3Price\">75,000원</div>  \n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <!-- 제품1-4 -->\n");
      out.write("                        <div class=\"BNitem Bitem4\">\n");
      out.write("                        	<p class=rank>4위</p>\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <div class=\"BNitemPic bestItem1Pic\">\n");
      out.write("                                    <figcaption>제품4<br><br> 상세설명칸<br><br> 입니다 </figcaption>\n");
      out.write("                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/index/제품_나우푸드c1000.jpg\" \n");
      out.write("                                    alt=\"제품사진\" id=\"bestItemPhoto4\">\n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("\n");
      out.write("                                <div class=\"BNitemName bestItem1Name\">\n");
      out.write("                                    <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분) </a>\n");
      out.write("                                </div>        \n");
      out.write("\n");
      out.write("                                <div class=\"BNitemPrice bestItem4Price\">75,000원</div>\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                    </div>\n");
      out.write("                \n");
      out.write("                    <!-- 2행 -->\n");
      out.write("                    <div class=\"line row2\">\n");
      out.write("                        <!--제품2-1 -->\n");
      out.write("                        <div class=\"BNitem Bitem1\">\n");
      out.write("                        	<p class=rank>5위</p>    \n");
      out.write("                            <a href=\"#\">    \n");
      out.write("                                <div class=\"BNitemPic bestItem1Pic\"> \n");
      out.write("                                    <figcaption>제품1<br><br> 상세설명칸<br><br> 입니다 </figcaption>\n");
      out.write("                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/index/제품_오쏘뮬.jpg\" \n");
      out.write("                                        alt=\"제품사진\" id=\"bestItemPhoto1\">\n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("                                <div class=\"BNitemName bestItem1Name\">\n");
      out.write("                                    <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>  \n");
      out.write("                                </div> \n");
      out.write("                            \n");
      out.write("                                <div class=\"BNitemPrice bestItem1Price\">75,000원</div>  \n");
      out.write("                        </div>                        \n");
      out.write("\n");
      out.write("                                                    \n");
      out.write("                        <!-- 제품2-2 --> \n");
      out.write("                        <div class=\"BNitem Bitem2\">\n");
      out.write("                        	<p class=rank>6위</p>  \n");
      out.write("                            <a href=\"#\">  \n");
      out.write("                                <div class=\"BNitemPic bestItem2Pic\">\n");
      out.write("                                    <figcaption>제품2<br><br> 상세설명칸<br><br> 입니다 </figcaption> \n");
      out.write("                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/index/제품_오쏘뮬.jpg\"\n");
      out.write("                                        alt=\"제품사진\" id=\"bestItemPhoto2\"> \n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("                                <div class=\"BNitemName bestItem2Name\">\n");
      out.write("                                    <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>\n");
      out.write("                                </div> \n");
      out.write("                            \n");
      out.write("                                <div class=\"BNitemPrice bestItem2Price\">75,000원</div>\n");
      out.write("                        </div>                       <!-- /li 1-->\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <!-- 제품2-3 -->\n");
      out.write("                        <div class=\"BNitem Bitem3\">\n");
      out.write("                        	<p class=rank>7위</p>\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <div class=\"BNitemPic bestItem3Pic\">\n");
      out.write("                                    <figcaption>제품3<br><br> 상세설명칸<br><br> 입니다 </figcaption>\n");
      out.write("                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/index/제품_오쏘뮬.jpg\"\n");
      out.write("                                    alt=\"제품사진\" id=\"bestItemPhoto3\">\n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("\n");
      out.write("                                <div class=\"BNitemName bestItem3Name\">\n");
      out.write("                                    <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>  \n");
      out.write("                                </div>\n");
      out.write("\n");
      out.write("                                <div class=\"BNitemPrice bestItem3Price\">75,000원</div>  \n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <!-- 제품2-4 -->\n");
      out.write("                        <div class=\"BNitem Bitem4\">\n");
      out.write("                        	<p class=rank>8위</p>\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <div class=\"BNitemPic bestItem1Pic\">\n");
      out.write("                                    <figcaption>제품4<br><br> 상세설명칸<br><br> 입니다 </figcaption>\n");
      out.write("                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/index/제품_오쏘뮬.jpg\"\n");
      out.write("                                    alt=\"제품사진\" id=\"bestItemPhoto4\">\n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("\n");
      out.write("                                <div class=\"BNitemName bestItem1Name\">\n");
      out.write("                                    <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분) </a>\n");
      out.write("                                </div>        \n");
      out.write("\n");
      out.write("                                <div class=\"BNitemPrice bestItem4Price\">75,000원</div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <!-- 3행 -->\n");
      out.write("                    <div class=\"line row3\">\n");
      out.write("                        <!--제품3-1 -->\n");
      out.write("                        <div class=\"BNitem Bitem1\">\n");
      out.write("                        	<p class=rank>9위</p>    \n");
      out.write("                            <a href=\"#\">    \n");
      out.write("                                <div class=\"BNitemPic bestItem1Pic\"> \n");
      out.write("                                    <figcaption>제품1<br><br> 상세설명칸<br><br> 입니다 </figcaption>\n");
      out.write("                                    <img src=\"resources/image/index/제품_오쏘뮬.jpg\"\n");
      out.write("                                        alt=\"제품사진\" id=\"bestItemPhoto1\">\n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("                                <div class=\"BNitemName bestItem1Name\">\n");
      out.write("                                    <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>  \n");
      out.write("                                </div> \n");
      out.write("                            \n");
      out.write("                                <div class=\"BNitemPrice bestItem1Price\">75,000원</div>  \n");
      out.write("                        </div>                        \n");
      out.write("\n");
      out.write("                                                   \n");
      out.write("                        <!-- 제품3-2 -->  \n");
      out.write("                        <div class=\"BNitem Bitem2\">\n");
      out.write("                        	<p class=rank>10위</p>      \n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <div class=\"BNitemPic bestItem2Pic\">\n");
      out.write("                                    <figcaption>제품2<br><br> 상세설명칸<br><br> 입니다 </figcaption>\n");
      out.write("                                    <img src=\"resources/image/index/제품_오쏘뮬.jpg\"\n");
      out.write("                                        alt=\"제품사진\" id=\"bestItemPhoto2\"> \n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("                                <div class=\"BNitemName bestItem2Name\">\n");
      out.write("                                    <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>\n");
      out.write("                                </div> \n");
      out.write("                            \n");
      out.write("                                <div class=\"BNitemPrice bestItem2Price\">75,000원</div>\n");
      out.write("                        </div>                       <!-- /li 1-->\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <!-- 제품3-3 -->\n");
      out.write("                        <div class=\"BNitem Bitem3\">\n");
      out.write("                        	<p class=rank>11위</p>\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <div class=\"BNitemPic bestItem3Pic\">\n");
      out.write("                                    <figcaption>제품3<br><br> 상세설명칸<br><br> 입니다 </figcaption>\n");
      out.write("                                    <img src=\"resources/image/index/제품_오쏘뮬.jpg\"\n");
      out.write("                                    alt=\"제품사진\" id=\"bestItemPhoto3\">\n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("\n");
      out.write("                                <div class=\"BNitemName bestItem3Name\">\n");
      out.write("                                    <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>  \n");
      out.write("                                </div>\n");
      out.write("\n");
      out.write("                                <div class=\"BNitemPrice bestItem3Price\">75,000원</div>  \n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <!-- 제품3-4 -->\n");
      out.write("                        <div class=\"BNitem Bitem4\">\n");
      out.write("                        	<p class=rank>12위</p>\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <div class=\"BNitemPic bestItem1Pic\">\n");
      out.write("                                    <figcaption>제품4<br><br> 상세설명칸<br><br> 입니다 </figcaption>\n");
      out.write("                                    <img src=\"resources/image/index/제품_오쏘뮬.jpg\"\n");
      out.write("                                    alt=\"제품사진\" id=\"bestItemPhoto4\">\n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("\n");
      out.write("                                <div class=\"BNitemName bestItem1Name\">\n");
      out.write("                                    <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분) </a>\n");
      out.write("                                </div>        \n");
      out.write("\n");
      out.write("                                <div class=\"BNitemPrice bestItem4Price\">75,000원</div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <!-- 4행 -->\n");
      out.write("                    <div class=\"line row4\">\n");
      out.write("                        <!--제품4-1 -->\n");
      out.write("                        <div class=\"BNitem Bitem1\">\n");
      out.write("                        	<p class=rank>13위</p>    \n");
      out.write("                            <a href=\"#\">    \n");
      out.write("                                <div class=\"BNitemPic bestItem1Pic\"> \n");
      out.write("                                    <figcaption>제품1<br><br> 상세설명칸<br><br> 입니다 </figcaption>\n");
      out.write("                                    <img src=\"resources/image/index/제품_오쏘뮬.jpg\"\n");
      out.write("                                        alt=\"제품사진\" id=\"bestItemPhoto1\">\n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("                                <div class=\"BNitemName bestItem1Name\">\n");
      out.write("                                    <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>  \n");
      out.write("                                </div> \n");
      out.write("                            \n");
      out.write("                                <div class=\"BNitemPrice bestItem1Price\">75,000원</div>  \n");
      out.write("                        </div>                        \n");
      out.write("\n");
      out.write("                                                   \n");
      out.write("                        <!-- 제품4-2 -->  \n");
      out.write("                        <div class=\"BNitem Bitem2\">\n");
      out.write("                        	<p class=rank>14위</p>  \n");
      out.write("                            <a href=\"#\"> \n");
      out.write("                                <div class=\"BNitemPic bestItem2Pic\">\n");
      out.write("                                    <figcaption>제품2<br><br> 상세설명칸<br><br> 입니다 </figcaption> \n");
      out.write("                                    <img src=\"resources/image/index/제품_오쏘뮬.jpg\"\n");
      out.write("                                        alt=\"제품사진\" id=\"bestItemPhoto2\"> \n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("                                <div class=\"BNitemName bestItem2Name\">\n");
      out.write("                                    <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>\n");
      out.write("                                </div> \n");
      out.write("                            \n");
      out.write("                                <div class=\"BNitemPrice bestItem2Price\">75,000원</div>\n");
      out.write("                        </div>                       \n");
      out.write("\n");
      out.write("\n");
      out.write("                        <!-- 제품4-3 -->\n");
      out.write("                        <div class=\"BNitem Bitem3\">\n");
      out.write("                        	<p class=rank>15위</p>\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <div class=\"BNitemPic bestItem3Pic\">\n");
      out.write("                                    <figcaption>제품3<br><br> 상세설명칸<br><br> 입니다 </figcaption>\n");
      out.write("                                    <img src=\"resources/image/index/제품_오쏘뮬.jpg\" \n");
      out.write("                                    alt=\"제품사진\" id=\"bestItemPhoto3\">\n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("\n");
      out.write("                                <div class=\"BNitemName bestItem3Name\">\n");
      out.write("                                    <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>  \n");
      out.write("                                </div>\n");
      out.write("\n");
      out.write("                                <div class=\"BNitemPrice bestItem3Price\">75,000원</div>  \n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <!-- 제품4-4 -->\n");
      out.write("                        <div class=\"BNitem Bitem4\">\n");
      out.write("                        	<p class=rank>16위</p>\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <div class=\"BNitemPic bestItem1Pic\">\n");
      out.write("                                    <figcaption>제품4<br><br> 상세설명칸<br><br> 입니다 </figcaption>\n");
      out.write("                                    <img src=\"resources/image/index/제품_오쏘뮬.jpg\" \n");
      out.write("                                    alt=\"제품사진\" id=\"bestItemPhoto4\">\n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("\n");
      out.write("                                <div class=\"BNitemName bestItem1Name\">\n");
      out.write("                                    <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분) </a>\n");
      out.write("                                </div>        \n");
      out.write("\n");
      out.write("                                <div class=\"BNitemPrice bestItem4Price\">75,000원</div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <!-- 5행 -->\n");
      out.write("                    <div class=\"line row5\">\n");
      out.write("                        <!--제품5-1 -->\n");
      out.write("                        <div class=\"BNitem Bitem1\">\n");
      out.write("                        	<p class=rank>17위</p>    \n");
      out.write("                            <a href=\"#\">    \n");
      out.write("                                <div class=\"BNitemPic bestItem1Pic\"> \n");
      out.write("                                    <figcaption>제품1<br><br> 상세설명칸<br><br> 입니다 </figcaption>\n");
      out.write("                                    <img src=\"resources/image/index/제품_오쏘뮬.jpg\" \n");
      out.write("                                        alt=\"제품사진\" id=\"bestItemPhoto1\">\n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("                                <div class=\"BNitemName bestItem1Name\">\n");
      out.write("                                    <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>  \n");
      out.write("                                </div> \n");
      out.write("                            \n");
      out.write("                                <div class=\"BNitemPrice bestItem1Price\">75,000원</div>  \n");
      out.write("                        </div>                        \n");
      out.write("\n");
      out.write("                                                    \n");
      out.write("                        <!-- 제품5-2 -->  \n");
      out.write("                        <div class=\"BNitem Bitem2\">\n");
      out.write("                        	<p class=rank>18위</p>\n");
      out.write("                            <a href=\"#\">  \n");
      out.write("                                <div class=\"BNitemPic bestItem2Pic\"> \n");
      out.write("                                    <figcaption>제품2<br><br> 상세설명칸<br><br> 입니다 </figcaption>\n");
      out.write("                                    <img src=\"resources/image/index/제품_오쏘뮬.jpg\" \n");
      out.write("                                        alt=\"제품사진\" id=\"bestItemPhoto2\"> \n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("                                <div class=\"BNitemName bestItem2Name\">\n");
      out.write("                                    <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>\n");
      out.write("                                </div> \n");
      out.write("                            \n");
      out.write("                                <div class=\"BNitemPrice bestItem2Price\">75,000원</div>\n");
      out.write("                        </div>                      \n");
      out.write("\n");
      out.write("\n");
      out.write("                        <!-- 제품5-3 -->\n");
      out.write("                        <div class=\"BNitem Bitem3\">\n");
      out.write("                        	<p class=rank>19위</p>\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <div class=\"BNitemPic bestItem3Pic\">\n");
      out.write("                                    <figcaption>제품3<br><br> 상세설명칸<br><br> 입니다 </figcaption>\n");
      out.write("                                    <img src=\"/assets/제품_오쏘뮬.jpg\"\n");
      out.write("                                    alt=\"제품사진\" id=\"bestItemPhoto3\">\n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("\n");
      out.write("                                <div class=\"BNitemName bestItem3Name\">\n");
      out.write("                                    <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>  \n");
      out.write("                                </div>\n");
      out.write("\n");
      out.write("                                <div class=\"BNitemPrice bestItem3Price\">75,000원</div>  \n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <!-- 제품5-4 -->\n");
      out.write("                        <div class=\"BNitem Bitem4\">\n");
      out.write("                        	<p class=rank>20위</p>\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <div class=\"BNitemPic bestItem1Pic\">\n");
      out.write("                                    <figcaption>제품4<br><br> 상세설명칸<br><br> 입니다 </figcaption>\n");
      out.write("                                    <img src=\"resources/image/index/제품_오쏘뮬.jpg\" \n");
      out.write("                                    alt=\"제품사진\" id=\"bestItemPhoto4\">\n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("\n");
      out.write("                                <div class=\"BNitemName bestItem1Name\">\n");
      out.write("                                    <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분) </a>\n");
      out.write("                                </div>        \n");
      out.write("\n");
      out.write("                                <div class=\"BNitemPrice bestItem4Price\">75,000원</div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <!-- 6행 -->\n");
      out.write("                    <div class=\"line row6\">\n");
      out.write("                        <!--제품6-1 -->\n");
      out.write("                        <div class=\"BNitem Bitem1\">\n");
      out.write("                        	<p class=rank>21위</p>    \n");
      out.write("                            <a href=\"#\">    \n");
      out.write("                                <div class=\"BNitemPic bestItem1Pic\"> \n");
      out.write("                                    <figcaption>제품1<br><br> 상세설명칸<br><br> 입니다 </figcaption>\n");
      out.write("                                    <img src=\"resources/image/index/제품_오쏘뮬.jpg\" \n");
      out.write("                                        alt=\"제품사진\" id=\"bestItemPhoto1\">\n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("                                <div class=\"BNitemName bestItem1Name\">\n");
      out.write("                                    <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>  \n");
      out.write("                                </div> \n");
      out.write("                            \n");
      out.write("                                <div class=\"BNitemPrice bestItem1Price\">75,000원</div>  \n");
      out.write("                        </div>                        \n");
      out.write("\n");
      out.write("                                                  \n");
      out.write("                        <!-- 제품6-2 -->  \n");
      out.write("                        <div class=\"BNitem Bitem2\">\n");
      out.write("                        	<p class=rank>22위</p>\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <div class=\"BNitemPic bestItem2Pic\"> \n");
      out.write("                                    <figcaption>제품2<br><br> 상세설명칸<br><br> 입니다 </figcaption>\n");
      out.write("                                    <img src=\"resources/image/index/제품_오쏘뮬.jpg\" \n");
      out.write("                                        alt=\"제품사진\" id=\"bestItemPhoto2\"> \n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("                                <div class=\"BNitemName bestItem2Name\">\n");
      out.write("                                    <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>\n");
      out.write("                                </div> \n");
      out.write("                            \n");
      out.write("                                <div class=\"BNitemPrice bestItem2Price\">75,000원</div>\n");
      out.write("                        </div>                      \n");
      out.write("\n");
      out.write("\n");
      out.write("                        <!-- 제품6-3 -->\n");
      out.write("                        <div class=\"BNitem Bitem3\">\n");
      out.write("                        	<p class=rank>23위</p>\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <div class=\"BNitemPic bestItem3Pic\">\n");
      out.write("                                    <figcaption>제품3<br><br> 상세설명칸<br><br> 입니다 </figcaption>\n");
      out.write("                                    <img src=\"resources/image/index/제품_오쏘뮬.jpg\" \n");
      out.write("                                    alt=\"제품사진\" id=\"bestItemPhoto3\">\n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("\n");
      out.write("                                <div class=\"BNitemName bestItem3Name\">\n");
      out.write("                                    <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>  \n");
      out.write("                                </div>\n");
      out.write("\n");
      out.write("                                <div class=\"BNitemPrice bestItem3Price\">75,000원</div>  \n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <!-- 제품6-4 -->\n");
      out.write("                        <div class=\"BNitem Bitem4\">\n");
      out.write("                        	<p class=rank>24위</p>\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <div class=\"BNitemPic bestItem1Pic\">\n");
      out.write("                                    <figcaption>제품4<br><br> 상세설명칸<br><br> 입니다 </figcaption>\n");
      out.write("                                    <img src=\"resources/image/index/제품_오쏘뮬.jpg\" \n");
      out.write("                                    alt=\"제품사진\" id=\"bestItemPhoto4\">\n");
      out.write("                                </div>\n");
      out.write("                            </a>\n");
      out.write("\n");
      out.write("                                <div class=\"BNitemName bestItem1Name\">\n");
      out.write("                                    <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분) </a>\n");
      out.write("                                </div>        \n");
      out.write("\n");
      out.write("                                <div class=\"BNitemPrice bestItem4Price\">75,000원</div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                \n");
      out.write("                \n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                <!-- 2-3 숫자 페이지네이션 -->\n");
      out.write("                <div class=\"numListBox\">\n");
      out.write("\n");
      out.write("                    <!-- 왼쪽 화살표버튼 -->\n");
      out.write("                    <div id=\"numListBtnBox\">\n");
      out.write("                        <button type=\"button\" id=\"movePrev\">\n");
      out.write("                           <span style=\"color: black;\">\n");
      out.write("                                <i class=\"fa-solid fa-less-than\"></i>\n");
      out.write("                           </span>\n");
      out.write("                        </button>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <!-- </div> -->\n");
      out.write("                    <div id=\"listBox\">\n");
      out.write("                        <a href=\"#\">1</a>\n");
      out.write("                        <a href=\"#\">2</a>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <!-- 오른쪽 화살표 -->\n");
      out.write("                    <div id=\"numListBtnBox2\">\n");
      out.write("                        <button type=\"button\" id=\"moveNext\">\n");
      out.write("                           <span style=\"color: black;\">\n");
      out.write("                                <i class=\"fa-solid fa-greater-than\"></i>\n");
      out.write("                           </span>\n");
      out.write("                        </button>\n");
      out.write("                    </div>\n");
      out.write("                   \n");
      out.write("                </div>\n");
      out.write("               \n");
      out.write("\n");
      out.write("            <!-- 가운데페이지 끝 -->\n");
      out.write("            </section>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("            <!-- 3. 오른쪽사이드바 -->\n");
      out.write("            <section class=\"rightSide\">\n");
      out.write("\n");
      out.write("                \n");
      out.write("                <!-- 인체사진 플로팅바-->\n");
      out.write("                <div class=\"floating\">\n");
      out.write("                    <a href=\"#\"> \n");
      out.write("                        <img id=\"people\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/index/인체이미지누끼.png\">\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("            </section>\n");
      out.write("\n");
      out.write("	\n");
      out.write("		</section>\n");
      out.write("        <!-- content 전체 감싸는 영역 끝 -->\n");
      out.write("		\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        \n");
      out.write("\n");
      out.write("    <!-- 헤더, 컨텐츠 끝 -->\n");
      out.write("    </main>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- 푸터 -->\n");
      out.write("  	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("	<!-- jQuery 라이브러리 추가 -->\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\" integrity=\"sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=\" crossorigin=\"anonymous\"></script>\n");
      out.write("     \n");
      out.write("     <!-- bestProduct.js 연결 -->\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/product/bestProduct.js\"></script> \n");
      out.write("   \n");
      out.write("    <!-- main.js 연결 -->\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/main.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
