/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-04-10 08:05:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class productDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1680738812000L));
    _jspx_dependants.put("jar:file:/Users/deokkeun/Desktop/YoSangSo-main/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/yosangso/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/main-style.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/productDetail.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/slick.css\">\n");
      out.write("   \n");
      out.write("    <script src=\"https://kit.fontawesome.com/881d1deef7.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-1.12.4.min.js\"></script>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    <title>productDetail</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <!-- 헤더, 컨텐츠 -->\n");
      out.write("    <main>\n");
      out.write("        \n");
      out.write("        <!-- 헤더 -->\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\n");
      out.write("        <br>\n");
      out.write("        <br>\n");
      out.write("        <br>\n");
      out.write("        \n");
      out.write("        <section class=\"mainsec\"> \n");
      out.write("            <div class=\"all\">\n");
      out.write("            <div>   \n");
      out.write("                <!--productdetails-->\n");
      out.write("                <!--제품 상세 컨테이너-->\n");
      out.write("                <div class=\"productdetails-container\">\n");
      out.write("                    <!--제품 이미지-->\n");
      out.write("                    <div class=\"product-img\">\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/product/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productList[0].productName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".jpg\">\n");
      out.write("                    </div>\n");
      out.write("                    <!--제품이름, 가격, 수량, 구매가격, 구매및 장바구니-->\n");
      out.write("                    <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order/payOne\" method=\"GET\" name=\"purcahse\">\n");
      out.write("	                    <div class =\"productover\">\n");
      out.write("	                        <!--제품이름-->\n");
      out.write("	                        <div class=\"productNm\">\n");
      out.write("	                            <h3>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productList[0].productName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\n");
      out.write("	                        </div>\n");
      out.write("	                        <!--가격-->\n");
      out.write("	                        <div class=\"productPr\">\n");
      out.write("	                            <span id=\"price\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productList[0].price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>원\n");
      out.write("	                        </div>\n");
      out.write("	                        <!--배송비-->\n");
      out.write("	                        <br>\n");
      out.write("	                        <br>\n");
      out.write("	                        <br>\n");
      out.write("	                        <br>\n");
      out.write("	                        <div class=\"del-cost\">\n");
      out.write("	                            배송비 :<input id=\"delcost\" value=\"3000\">원\n");
      out.write("	                        </div>\n");
      out.write("	                        <br>\n");
      out.write("	                        <hr>\n");
      out.write("	                        <!--수량 가격-->\n");
      out.write("	                        <div class=\"count\">\n");
      out.write("	                            수량 : <input type=\"number\" id=\"countbox\" min=\"1\" name=\"count\">\n");
      out.write("	                        </div>\n");
      out.write("	                        <br>\n");
      out.write("	                        <hr>\n");
      out.write("	                        <!--총 금액-->\n");
      out.write("	                        <div class=\"total-cost\">\n");
      out.write("	                            <pre>총 상품금액</pre>\n");
      out.write("	                            <span id=\"totalcost\"></span>원\n");
      out.write("	                        </div>\n");
      out.write("	                  \n");
      out.write("	                        <input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productList[0].productNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"productNo\" id=\"proNo\">\n");
      out.write("	                        \n");
      out.write("	                        <input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember.memberNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"loginmember\" id=\"loginmember\">\n");
      out.write("	                        <br>\n");
      out.write("                            <!--구매 버튼-->\n");
      out.write("                            <div>\n");
      out.write("	                            <button type=\"submit\" id=\"btn-purchase\">구매하기</button>\n");
      out.write("                            </div>\n");
      out.write("	                            \n");
      out.write("                     </form>       \n");
      out.write("                            <br>\n");
      out.write("                            <div>\n");
      out.write("                            <!--장바구니 버튼-->\n");
      out.write("                           	<button type=\"button\"  onclick=\"return addcart()\" id=\"btn-addcart\">장바구니</button>\n");
      out.write("           \n");
      out.write("                            </div>   \n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <br>\n");
      out.write("                <br>\n");
      out.write("                <br>\n");
      out.write("                <p id=\"product-detail\"></p>\n");
      out.write("                <br>\n");
      out.write("                <br>\n");
      out.write("                <br>\n");
      out.write("                <br>\n");
      out.write("                <br>\n");
      out.write("            \n");
      out.write("                    <!--상세정보, 리뷰 ,문의하기로 화면을 이동해주는 버튼-->\n");
      out.write("                    <div class=\"fm\">\n");
      out.write("                    <div class=\"fastmove\">\n");
      out.write("                        <a href=\"#product-detail\">상세정보</a>\n");
      out.write("                        <a href=\"#review\">리뷰</a>\n");
      out.write("                        <a href=\"#FAQ\">문의하기</a>\n");
      out.write("                    </div>\n");
      out.write("                    <hr>\n");
      out.write("                    </div>\n");
      out.write("                <br>\n");
      out.write("                <br>\n");
      out.write("                <br>\n");
      out.write("                <!--상품정보-->\n");
      out.write("                <div class=\"product-detail\">\n");
      out.write("                    <h2>상품 설명</h2>\n");
      out.write("                    <br>\n");
      out.write("                    <br>\n");
      out.write("                    \n");
      out.write("                    <span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productList[0].explain}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\n");
      out.write("                </div>\n");
      out.write("                <br>\n");
      out.write("                <br>\n");
      out.write("                <br>\n");
      out.write("                <br>\n");
      out.write("                <br>\n");
      out.write("                <br>\n");
      out.write("            \n");
      out.write("                <!--추천 상품-->\n");
      out.write("\n");
      out.write("               <!--추천 상품-->\n");
      out.write("               <div id=\"slideContainer\">\n");
      out.write("        \n");
      out.write("                <div class=\"items\">\n");
      out.write("                    <button class=\"prev\"><</button>\n");
      out.write("                    <div class=\"item active\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/product/Codeage, Fermented, 남성용 종합비타민, 캡슐 120정.jpg\"></div>\n");
      out.write("                    <div class=\"item\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/product/Codeage, 비타민, 메디테이트, 캡슐 60정정.jpg\"></div>\n");
      out.write("                    <div class=\"item\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/product/Codeage, 비타민, 모발, 비오틴, 콜라겐. 케라틴, 캡슐 120정.jpg\"></div>\n");
      out.write("                    <div class=\"item\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/product/Codeage, 비타민, 헤어 구미젤리, 무설탕, 비오틴, 비타민 C, 미네랄, 딸기 코코넛, 60개.jpg\"></div>\n");
      out.write("                    <button class=\"next\">></button>\n");
      out.write("                </div>\n");
      out.write("                    <div class=\"stepper\">\n");
      out.write("                    <div class=\"step active-step\"></div>\n");
      out.write("                    <div class=\"step\"></div>\n");
      out.write("                        <div class=\"step\"></div>\n");
      out.write("                <div class=\"step\"></div>\n");
      out.write("                </div>  \n");
      out.write("                </div>\n");
      out.write("                <p id=\"review\"></p>\n");
      out.write("                <br>\n");
      out.write("                <br>\n");
      out.write("                <br>\n");
      out.write("                <br>\n");
      out.write("            \n");
      out.write("                <!--productdetails end-->\n");
      out.write("            \n");
      out.write("                <!--review-->\n");
      out.write("                <!--리뷰 컨테이너-->\n");
      out.write("                <div class=\"review-container\">\n");
      out.write("                    <h2>구매후기</h2>\n");
      out.write("                    <!--리뷰 1-->\n");
      out.write("                    <div>\n");
      out.write("                        <!--고객 아이콘 이름 게시일-->\n");
      out.write("                        <div class=\"review-all\">\n");
      out.write("                            <!--고객 아이콘-->\n");
      out.write("                            <div class=\"review-icon\"><i class=\"fa-solid fa-circle-user\"></i></div>\n");
      out.write("                            <!--고객 이름-->\n");
      out.write("                            <div class=\"review-name\">윤현식</div>\n");
      out.write("                            <!--게시일-->\n");
      out.write("                            <div class=\"review-date\"><input type=\"date\"></div>\n");
      out.write("                        </div>\n");
      out.write("            \n");
      out.write("                        <!--리뷰 내용-->\n");
      out.write("                        <div class=\"review-main\">\n");
      out.write("                            <img src=\"/assets/re1.jpeg\">\n");
      out.write("                            <div>\n");
      out.write("                                <pre class=\"review-con\">\n");
      out.write("                        유통기한이 넉넉해서 미리 구입했는데 품절이네요 이제품 2년째 복용중입니다 일단은 얼굴이마주름이 현저히 없어져서 저도 \n");
      out.write("                        놀랄 정도구요 특히 무릎관절통증도 거의 사라졌어요 장기복용이 정답입니다 꾸준히 복용 해보세요.\n");
      out.write("                                </pre>\n");
      out.write("                            </div>    \n");
      out.write("                        </div>\n");
      out.write("            \n");
      out.write("                    </div>\n");
      out.write("                    <br>\n");
      out.write("                    <br>\n");
      out.write("                    <!--리뷰 2-->\n");
      out.write("                    <div>\n");
      out.write("                        <!--고객 아이콘 이름 게시일-->\n");
      out.write("                        <div class=\"review-all\">\n");
      out.write("                            <!--고객 아이콘-->\n");
      out.write("                            <div class=\"review-icon\"><i class=\"fa-solid fa-circle-user\"></i></div>\n");
      out.write("                            <!--고객 이름-->\n");
      out.write("                            <div class=\"review-name\">최훈석</div>\n");
      out.write("                            <!--게시일-->\n");
      out.write("                            <div class=\"review-date\"><input type=\"date\"></div>\n");
      out.write("                        </div>\n");
      out.write("            \n");
      out.write("                        <!--리뷰 내용-->\n");
      out.write("                        <div class=\"review-main\">\n");
      out.write("                            <img src=\"/assets/re2.jpeg\">\n");
      out.write("                            <pre class=\"review-con\">\n");
      out.write("                        저분자 피쉬 콜라겐에 비타민c와 히알루론산까지 들어있는 제품이고 믿고 먹는 품질의 브랜드라 구매했어요 피부가 맑아지고 확실히\n");
      out.write("                        효과 있어요 나이가 들면서 콜라겐이 줄어들기때문에 꾸준히 복용하려구요 한스푼에 물이나 음료 300ml 섞어서 먹으면 되요        \n");
      out.write("                            </pre>\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("            \n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <!--review end-->\n");
      out.write("            \n");
      out.write("                <br>\n");
      out.write("                 <p id=\"FAQ\"></p>\n");
      out.write("                <br>\n");
      out.write("                <br>\n");
      out.write("                <br>\n");
      out.write("            \n");
      out.write("                <!--FAQ-->\n");
      out.write("                <!--FAQ 컨테이너-->\n");
      out.write("                \n");
      out.write("                <div class=\"FAQ-container\">\n");
      out.write("                    <h2>FAQ</h2>\n");
      out.write("                    <!--FAQ1-->\n");
      out.write("                    <div>\n");
      out.write("                        <!--고객 아이콘, 이름, 게시일-->\n");
      out.write("                        <div class=\"FAQ-all\">\n");
      out.write("                            <!--고객 아이콘-->\n");
      out.write("                            <div class=\"FAQ-icon\"><i class=\"fa-solid fa-circle-user\"></i></div>\n");
      out.write("                            <!-- 고객 이름-->\n");
      out.write("                            <div class=\"FAQ-name\">김연수</div>\n");
      out.write("                            <!-- 게시일-->\n");
      out.write("                            <div class=\"FAQ-date\"><input type=\"date\"></div>\n");
      out.write("                        </div>\n");
      out.write("            \n");
      out.write("                        <!-- 질문 내용-->\n");
      out.write("                    <div id=\"Accordion_wrap\">\n");
      out.write("                        <div class=\"que\">\n");
      out.write("                         <span>하루에 몇 달톤을 먹어야 하나요?</span>\n");
      out.write("                          <div class=\"arrow-wrap\">\n");
      out.write("                            <span class=\"arrow-top\">↑</span>\n");
      out.write("                           <span class=\"arrow-bottom\">↓</span>\n");
      out.write("                          </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"anw\">\n");
      out.write("                         <span>하루에 300 달톤씩 복용하시면 됩니다</span>   \n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("            \n");
      out.write("                    <div>\n");
      out.write("                        <!--고객 아이콘, 이름, 게시일-->\n");
      out.write("                        <div class=\"FAQ-all\">\n");
      out.write("                            <!--고객 아이콘-->\n");
      out.write("                            <div class=\"FAQ-icon\"><i class=\"fa-solid fa-circle-user\"></i></div>\n");
      out.write("                            <!-- 고객 이름-->\n");
      out.write("                            <div class=\"FAQ-name\">하현성</div>\n");
      out.write("                            <!-- 게시일-->\n");
      out.write("                            <div class=\"FAQ-date\"><input type=\"date\"></div>\n");
      out.write("                        </div>\n");
      out.write("            \n");
      out.write("                        <!-- 질문 내용-->\n");
      out.write("                    <div id=\"Accordion_wrap\">\n");
      out.write("                        <div class=\"que\">\n");
      out.write("                         <span>먹고나서 부작용이 있는거 같아요</span>\n");
      out.write("                          <div class=\"arrow-wrap\">\n");
      out.write("                            <span class=\"arrow-top\">↑</span>\n");
      out.write("                           <span class=\"arrow-bottom\">↓</span>\n");
      out.write("                          </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"anw\">\n");
      out.write("                         <span>즉시 복용 중지 후 병원을 찾아가 주세요</span>   \n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            \n");
      out.write("            \n");
      out.write("        </section> \n");
      out.write("        \n");
      out.write("        \n");
      out.write("\n");
      out.write("        \n");
      out.write("       \n");
      out.write("       \n");
      out.write("		<br>\n");
      out.write("		<br>\n");
      out.write("		<br>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        \n");
      out.write("\n");
      out.write("    <!-- 헤더, 컨텐츠 끝 -->\n");
      out.write("    </main>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- 푸터 -->\n");
      out.write("  	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("	<!-- jQuery 라이브러리 추가 -->\n");
      out.write("    \n");
      out.write("   \n");
      out.write("    <!-- main.js 연결 -->\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/main.js\"></script>\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/slick.js\"></script>\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/productDetail.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
